import Mathlib
open CategoryTheory

/-
\begin{definition}[Braid groupoid, $\T$]
\label{def:T}
 $\T$ is the \textit{braid groupoid}. Informally,
 it represents braids from the braid group where
 each strand is labeled; two braids can compose
 only when their labels line up.

 Its objects are sequences of \textit{distinct} letters, where
 each letter labels a strand. This is a slight modification of $\K{}$'s
 objects, which allow duplicate letters. Because $\K{}$'s
 object monoid is free, we can
 easily rename strands to make a distinct sequence
 to represent some braid from $\K{}$ in $\T{}.$
 % The first and last
 % braids in Figure~\ref{fig:braid-canon-example} are
 % equivalent words in $\T{}.$
 We often label strands by which box they connect
 to and index them by their total order from
 that box.


$\T{}$'s morphisms are generated by
crossings of two strands.
For any
$\alpha, \beta$ that are
possibly empty sequences of distinct letters
not containing the
letters $c, d,$ there is a generator
$\gen{c}{d}{} : \alpha{}cd\beta
\to \alpha{}dc\beta$
that crosses strand $c$ over strand $d.$ $\gen{c}{d}{p}$
is defined for any sequence $p$ where
$c$ is directly to the left of $d.$ See
Figure~\ref{fig:T-gen}
for an example of $\gen{c}{d}{} : \alpha{}cd\beta
\to \alpha{}dc\beta.$
In the notation of $\K{},$ we would write
$\gen{c}{d}{} : \alpha{}cd\beta
\to \alpha{}dc\beta$ as
$\id{}_{\alpha} \otimes \sigma_{[c],[d]} \otimes \id{}_{\beta}.$

% \begin{figure}[h]
%     \centering
%     \includegraphics[width=0.5\linewidth]{figs_not_from_python/alpha-x-y-beta.pdf}
%     \caption{Diagrammatic
%     representation of $\gen{c}{d}{} : \alpha{}cd\beta \to \alpha{}dc\beta$
%     for $|\alpha| = 3, |\beta|=5.$
%     The strands in $\alpha, \beta$ do not move,
%     and only $c, d$ cross.}
%     \label{fig:T-gen}
% \end{figure}

Note that the domain and the crossed strands $c, d$ uniquely
determine the codomain. Hence
for some sequence of strands $p$ that contains $[c, d],$
we can describe a
unique generator $\gen{c}{d}{p}.$
When context allows, we omit the object
$p$ and refer to some class of generators
$\gen{c}{d}{},$ which all cross $c$ over
$d$ but differ in the strands to the left
and right of $c, d.$
The identity braid (no crossings)
for any sequence object
$p$ is denoted as $\id{}_p : p \to p$.  Similarly, we denote
an identity morphism, regardless of object, with
$\id{}.$

 $\T$ has commutative diagrams
 (the category-theoretic analog of the
 equations in the presentation of a
 group) for
 the shift-past commuting relation
 $$
  \gen{a}{b}{} ; \gen{c}{d}{}
  =
  \gen{c}{d}{} ; \gen{a}{b}{}
 $$
 and the Yang-Baxter equation
 $$
  \gen{a}{b}{}
  ; \gen{a}{c}{}
  ; \gen{b}{c}{}
  =
  \gen{b}{c}{}
  ; \gen{a}{c}{}
  ; \gen{a}{b}{},
 $$ where $a,b,c,d$ are distinct in both. These relations correspond to diagram moves \Btwo{} and
 \Bthree{} respectively, and \Bone{} arises from
 every braid being invertible.
 \end{definition}
-/

-- Implement the braid groupoid. You should follow the same structure
-- as in FreeMonoidal.lean: define the object monoid for a generic type α,
-- then the morphisms, then the commutative diagrams. Because this is the
-- braid groupoid, the extra morphisms will be the σ crossings and inverses,
-- and extra commutative diagrams will be for the commuting, yang-baxter, and
-- inverses. Then provide a named instance of Category, then of MonoidalCategory.

universe u

namespace BraidGroupoid

open MonoidalCategory

variable {α : Type u}

section

variable (α)

set_option genSizeOfSpec false in
set_option genInjectivity false in
/-- Objects for the braid groupoid: formal tensors of letters with a unit. -/
inductive Obj : Type u
    | of : α → Obj
    | unit : Obj
    | tensor : Obj → Obj → Obj
    deriving Inhabited

end

local notation "B" => Obj

/-- Formal braids generated by crossings, associators, and unitors. -/
inductive Hom : B α → B α → Type u
    | id (X) : Hom X X
    | α_hom (X Y Z : B α) : Hom ((X.tensor Y).tensor Z) (X.tensor (Y.tensor Z))
    | α_inv (X Y Z : B α) : Hom (X.tensor (Y.tensor Z)) ((X.tensor Y).tensor Z)
    | l_hom (X) : Hom (Obj.unit.tensor X) X
    | l_inv (X) : Hom X (Obj.unit.tensor X)
    | ρ_hom (X) : Hom (X.tensor Obj.unit) X
    | ρ_inv (X) : Hom X (X.tensor Obj.unit)
    | σ (X Y : B α) : Hom (X.tensor Y) (Y.tensor X)
    | σ_inv (X Y : B α) : Hom (Y.tensor X) (X.tensor Y)
    | comp {X Y Z} (f : Hom X Y) (g : Hom Y Z) : Hom X Z
    | whiskerLeft (X : B α) {Y₁ Y₂} (f : Hom Y₁ Y₂) : Hom (X.tensor Y₁) (X.tensor Y₂)
    | whiskerRight {X₁ X₂} (f : Hom X₁ X₂) (Y : B α) : Hom (X₁.tensor Y) (X₂.tensor Y)
    | tensor {W X Y Z} (f : Hom W Y) (g : Hom X Z) : Hom (W.tensor X) (Y.tensor Z)

local infixr:10 " ⟶ᵇ " => Hom

def yangBaxterLeft (X Y Z : B α) : (X.tensor Y).tensor Z ⟶ᵇ (Z.tensor Y).tensor X :=
    Hom.comp
        (Hom.comp
            (Hom.comp
                (Hom.comp
                    (Hom.whiskerRight (Hom.σ X Y) Z)
                    (Hom.α_hom Y X Z))
                (Hom.whiskerLeft Y (Hom.σ X Z)))
            (Hom.α_inv Y Z X))
        (Hom.whiskerRight (Hom.σ Y Z) X)

def yangBaxterRight (X Y Z : B α) : (X.tensor Y).tensor Z ⟶ᵇ (Z.tensor Y).tensor X :=
    Hom.comp
        (Hom.comp
            (Hom.comp
                (Hom.comp
                    (Hom.comp
                        (Hom.comp
                            (Hom.α_hom X Y Z)
                            (Hom.whiskerLeft X (Hom.σ Y Z)))
                        (Hom.α_inv X Z Y))
                    (Hom.whiskerRight (Hom.σ X Z) Y))
                (Hom.α_hom Z X Y))
            (Hom.whiskerLeft Z (Hom.σ X Y)))
        (Hom.α_inv Z Y X)

/-- Relations for the braid groupoid. -/
inductive HomEquiv : ∀ {X Y : B α}, (X ⟶ᵇ Y) → (X ⟶ᵇ Y) → Prop
    | refl {X Y} (f : X ⟶ᵇ Y) : HomEquiv f f
    | symm {X Y} (f g : X ⟶ᵇ Y) : HomEquiv f g → HomEquiv g f
    | trans {X Y} {f g h : X ⟶ᵇ Y} : HomEquiv f g → HomEquiv g h → HomEquiv f h
    | comp {X Y Z} {f f' : X ⟶ᵇ Y} {g g' : Y ⟶ᵇ Z} :
            HomEquiv f f' → HomEquiv g g' → HomEquiv (f.comp g) (f'.comp g')
    | whiskerLeft (X) {Y Z} (f f' : Y ⟶ᵇ Z) :
            HomEquiv f f' → HomEquiv (f.whiskerLeft X) (f'.whiskerLeft X)
    | whiskerRight {Y Z} (f f' : Y ⟶ᵇ Z) (X) :
            HomEquiv f f' → HomEquiv (f.whiskerRight X) (f'.whiskerRight X)
    | tensor {W X Y Z} {f f' : W ⟶ᵇ X} {g g' : Y ⟶ᵇ Z} :
            HomEquiv f f' → HomEquiv g g' → HomEquiv (f.tensor g) (f'.tensor g')
    | tensorHom_def {X₁ Y₁ X₂ Y₂} (f : X₁ ⟶ᵇ Y₁) (g : X₂ ⟶ᵇ Y₂) :
            HomEquiv (f.tensor g) ((f.whiskerRight X₂).comp (g.whiskerLeft Y₁))
    | comp_id {X Y} (f : X ⟶ᵇ Y) : HomEquiv (f.comp (Hom.id _)) f
    | id_comp {X Y} (f : X ⟶ᵇ Y) : HomEquiv ((Hom.id _).comp f) f
    | assoc {X Y U V : B α} (f : X ⟶ᵇ U) (g : U ⟶ᵇ V) (h : V ⟶ᵇ Y) :
            HomEquiv ((f.comp g).comp h) (f.comp (g.comp h))
    | id_tensorHom_id {X Y} : HomEquiv ((Hom.id X).tensor (Hom.id Y)) (Hom.id _)
    | tensorHom_comp_tensorHom {X₁ Y₁ Z₁ X₂ Y₂ Z₂ : B α} (f₁ : X₁ ⟶ᵇ Y₁) (f₂ : X₂ ⟶ᵇ Y₂)
            (g₁ : Y₁ ⟶ᵇ Z₁) (g₂ : Y₂ ⟶ᵇ Z₂) :
        HomEquiv ((f₁.tensor f₂).comp (g₁.tensor g₂)) ((f₁.comp g₁).tensor (f₂.comp g₂))
    | whiskerLeft_id (X Y) : HomEquiv ((Hom.id Y).whiskerLeft X) (Hom.id (X.tensor Y))
    | id_whiskerRight (X Y) : HomEquiv ((Hom.id X).whiskerRight Y) (Hom.id (X.tensor Y))
    | α_hom_inv {X Y Z} : HomEquiv ((Hom.α_hom X Y Z).comp (Hom.α_inv X Y Z)) (Hom.id _)
    | α_inv_hom {X Y Z} : HomEquiv ((Hom.α_inv X Y Z).comp (Hom.α_hom X Y Z)) (Hom.id _)
    | associator_naturality {X₁ X₂ X₃ Y₁ Y₂ Y₃}
            (f₁ : X₁ ⟶ᵇ Y₁) (f₂ : X₂ ⟶ᵇ Y₂) (f₃ : X₃ ⟶ᵇ Y₃) :
            HomEquiv (((f₁.tensor f₂).tensor f₃).comp (Hom.α_hom Y₁ Y₂ Y₃))
                ((Hom.α_hom X₁ X₂ X₃).comp (f₁.tensor (f₂.tensor f₃)))
    | ρ_hom_inv {X} : HomEquiv ((Hom.ρ_hom X).comp (Hom.ρ_inv X)) (Hom.id _)
    | ρ_inv_hom {X} : HomEquiv ((Hom.ρ_inv X).comp (Hom.ρ_hom X)) (Hom.id _)
    | ρ_naturality {X Y} (f : X ⟶ᵇ Y) :
            HomEquiv ((f.whiskerRight Obj.unit).comp (Hom.ρ_hom Y)) ((Hom.ρ_hom X).comp f)
    | l_hom_inv {X} : HomEquiv ((Hom.l_hom X).comp (Hom.l_inv X)) (Hom.id _)
    | l_inv_hom {X} : HomEquiv ((Hom.l_inv X).comp (Hom.l_hom X)) (Hom.id _)
    | l_naturality {X Y} (f : X ⟶ᵇ Y) :
            HomEquiv ((f.whiskerLeft Obj.unit).comp (Hom.l_hom Y)) ((Hom.l_hom X).comp f)
    | pentagon {W X Y Z} :
            HomEquiv
                (((Hom.α_hom W X Y).whiskerRight Z).comp
                    ((Hom.α_hom W (X.tensor Y) Z).comp ((Hom.α_hom X Y Z).whiskerLeft W)))
                ((Hom.α_hom (W.tensor X) Y Z).comp (Hom.α_hom W X (Y.tensor Z)))
    | triangle {X Y} :
            HomEquiv ((Hom.α_hom X Obj.unit Y).comp ((Hom.l_hom Y).whiskerLeft X))
                ((Hom.ρ_hom X).whiskerRight Y)
    | σ_inv_left {X Y} : HomEquiv ((Hom.σ X Y).comp (Hom.σ_inv X Y)) (Hom.id _)
    | σ_inv_right {X Y} : HomEquiv ((Hom.σ_inv X Y).comp (Hom.σ X Y)) (Hom.id _)
    | σ_comm {X Y Z W} :
            HomEquiv
                (((Hom.σ X Y).whiskerRight (Z.tensor W)).comp
                    ((Hom.σ Z W).whiskerLeft (Y.tensor X)))
                (((Hom.σ Z W).whiskerLeft (X.tensor Y)).comp
                    ((Hom.σ X Y).whiskerRight (W.tensor Z)))
    | yang_baxter {X Y Z} :
            HomEquiv (yangBaxterLeft X Y Z) (yangBaxterRight X Y Z)

/-- Setoid for braid morphisms. -/
def setoidHom (X Y : B α) : Setoid (X ⟶ᵇ Y) :=
    ⟨HomEquiv, ⟨HomEquiv.refl, HomEquiv.symm _ _, HomEquiv.trans⟩⟩

attribute [instance] setoidHom

section

open HomEquiv

instance categoryBraidGroupoid : Category.{u} (B α) where
    Hom X Y := Quotient (BraidGroupoid.setoidHom X Y)
    id X := ⟦Hom.id X⟧
    comp := Quotient.map₂ Hom.comp (fun _ _ hf _ _ hg ↦ HomEquiv.comp hf hg)
    id_comp := by
        rintro X Y ⟨f⟩
        exact Quotient.sound (id_comp f)
    comp_id := by
        rintro X Y ⟨f⟩
        exact Quotient.sound (comp_id f)
    assoc := by
        rintro W X Y Z ⟨f⟩ ⟨g⟩ ⟨h⟩
        exact Quotient.sound (assoc f g h)

instance : MonoidalCategory (B α) where
    tensorObj X Y := Obj.tensor X Y
    tensorHom := Quotient.map₂ Hom.tensor (fun _ _ hf _ _ hg ↦ HomEquiv.tensor hf hg)
    whiskerLeft X _ _ f :=
        Quot.map (fun f ↦ Hom.whiskerLeft X f) (fun f f' ↦ .whiskerLeft X f f') f
    whiskerRight f Y :=
        Quot.map (fun f ↦ Hom.whiskerRight f Y) (fun f f' ↦ .whiskerRight f f' Y) f
    tensorHom_def {W X Y Z} := by
        rintro ⟨f⟩ ⟨g⟩
        exact Quotient.sound (tensorHom_def _ _)
    id_tensorHom_id _ _ := Quot.sound id_tensorHom_id
    tensorHom_comp_tensorHom {X₁ Y₁ Z₁ X₂ Y₂ Z₂} := by
        rintro ⟨f₁⟩ ⟨f₂⟩ ⟨g₁⟩ ⟨g₂⟩
        exact Quotient.sound (tensorHom_comp_tensorHom _ _ _ _)
    whiskerLeft_id X Y := Quot.sound (HomEquiv.whiskerLeft_id X Y)
    id_whiskerRight X Y := Quot.sound (HomEquiv.id_whiskerRight X Y)
    tensorUnit := Obj.unit
    associator X Y Z :=
        ⟨⟦Hom.α_hom X Y Z⟧, ⟦Hom.α_inv X Y Z⟧, Quotient.sound α_hom_inv,
            Quotient.sound α_inv_hom⟩
    associator_naturality {X₁ X₂ X₃ Y₁ Y₂ Y₃} := by
        rintro ⟨f₁⟩ ⟨f₂⟩ ⟨f₃⟩
        exact Quotient.sound (associator_naturality _ _ _)
    leftUnitor X :=
        ⟨⟦Hom.l_hom X⟧, ⟦Hom.l_inv X⟧, Quotient.sound l_hom_inv,
            Quotient.sound l_inv_hom⟩
    leftUnitor_naturality {X Y} := by
        rintro ⟨f⟩
        exact Quotient.sound (l_naturality _)
    rightUnitor X :=
        ⟨⟦Hom.ρ_hom X⟧, ⟦Hom.ρ_inv X⟧, Quotient.sound ρ_hom_inv,
            Quotient.sound ρ_inv_hom⟩
    rightUnitor_naturality {X Y} := by
        rintro ⟨f⟩
        exact Quotient.sound (ρ_naturality _)
    pentagon _ _ _ _ := Quotient.sound pentagon
    triangle _ _ := Quotient.sound triangle

end

end BraidGroupoid
