import Mathlib
open CategoryTheory

/-
\begin{definition}[Braid groupoid, $\T$]
\label{def:T}
 $\T$ is the \textit{braid groupoid}. Informally,
 it represents braids from the braid group where
 each strand is labeled; two braids can compose
 only when their labels line up.

 Its objects are sequences of \textit{distinct} letters, where
 each letter labels a strand. This is a slight modification of $\K{}$'s
 objects, which allow duplicate letters. Because $\K{}$'s
 object monoid is free, we can
 easily rename strands to make a distinct sequence
 to represent some braid from $\K{}$ in $\T{}.$
 % The first and last
 % braids in Figure~\ref{fig:braid-canon-example} are
 % equivalent words in $\T{}.$
 We often label strands by which box they connect
 to and index them by their total order from
 that box.


$\T{}$'s morphisms are generated by
crossings of two strands.
For any
$\alpha, \beta$ that are
possibly empty sequences of distinct letters
not containing the
letters $c, d,$ there is a generator
$\gen{c}{d}{} : \alpha{}cd\beta
\to \alpha{}dc\beta$
that crosses strand $c$ over strand $d.$ $\gen{c}{d}{p}$
is defined for any sequence $p$ where
$c$ is directly to the left of $d.$ See
Figure~\ref{fig:T-gen}
for an example of $\gen{c}{d}{} : \alpha{}cd\beta
\to \alpha{}dc\beta.$
In the notation of $\K{},$ we would write
$\gen{c}{d}{} : \alpha{}cd\beta
\to \alpha{}dc\beta$ as
$\id{}_{\alpha} \otimes \sigma_{[c],[d]} \otimes \id{}_{\beta}.$

% \begin{figure}[h]
%     \centering
%     \includegraphics[width=0.5\linewidth]{figs_not_from_python/alpha-x-y-beta.pdf}
%     \caption{Diagrammatic
%     representation of $\gen{c}{d}{} : \alpha{}cd\beta \to \alpha{}dc\beta$
%     for $|\alpha| = 3, |\beta|=5.$
%     The strands in $\alpha, \beta$ do not move,
%     and only $c, d$ cross.}
%     \label{fig:T-gen}
% \end{figure}

Note that the domain and the crossed strands $c, d$ uniquely
determine the codomain. Hence
for some sequence of strands $p$ that contains $[c, d],$
we can describe a
unique generator $\gen{c}{d}{p}.$
When context allows, we omit the object
$p$ and refer to some class of generators
$\gen{c}{d}{},$ which all cross $c$ over
$d$ but differ in the strands to the left
and right of $c, d.$
The identity braid (no crossings)
for any sequence object
$p$ is denoted as $\id{}_p : p \to p$.  Similarly, we denote
an identity morphism, regardless of object, with
$\id{}.$

 $\T$ has commutative diagrams
 (the category-theoretic analog of the
 equations in the presentation of a
 group) for
 the shift-past commuting relation
 $$
  \gen{a}{b}{} ; \gen{c}{d}{}
  =
  \gen{c}{d}{} ; \gen{a}{b}{}
 $$
 and the Yang-Baxter equation
 $$
  \gen{a}{b}{}
  ; \gen{a}{c}{}
  ; \gen{b}{c}{}
  =
  \gen{b}{c}{}
  ; \gen{a}{c}{}
  ; \gen{a}{b}{},
 $$ where $a,b,c,d$ are distinct in both. These relations correspond to diagram moves \Btwo{} and
 \Bthree{} respectively, and \Bone{} arises from
 every braid being invertible.
 \end{definition}
-/

-- Implement the braid groupoid. You should supply a quotient type
-- "BraidGroupoid : List α → List α → Type", and then define
-- instance : Groupoid (List α) where
-- ...

universe u

def swapList {α : Type u} (left : List α) (a b : α) (right : List α) : List α :=
    left ++ a :: b :: right

lemma swapList_assoc {α : Type u} (left mid right : List α) (a b c d : α) :
        swapList (left ++ a :: b :: mid) c d right =
            swapList left a b (mid ++ c :: d :: right) := by
    induction left with
    | nil =>
      simp [swapList]
    | cons x xs ih =>
            simp [swapList]

lemma swapList_shift {α : Type u} (left right : List α) (a b c : α) :
    swapList left a b (c :: right) = swapList (left ++ [a]) b c right := by
  induction left with
  | nil =>
      simp [swapList]
  | cons x xs ih =>
      simp [swapList]

inductive BraidExpr (α : Type u) : List α → List α → Type u
    | id (p : List α) : BraidExpr α p p
    | comp {p q r q' : List α} (f : BraidExpr α p q) (g : BraidExpr α q' r) (h : q = q') :
            BraidExpr α p r
    | gen (left right : List α) (a b : α) :
            BraidExpr α (swapList left a b right) (swapList left b a right)
    | inv {p q : List α} (f : BraidExpr α p q) : BraidExpr α q p

def castBraid {α : Type u} {p q p' q' : List α}
        (hp : p = p') (hq : q = q') : BraidExpr α p q → BraidExpr α p' q' := by
    intro f
    cases hp
    cases hq
    exact f

inductive BraidRel {α : Type u} : {p q : List α} → BraidExpr α p q → BraidExpr α p q → Prop
    | refl {p q} (f : BraidExpr α p q) : BraidRel f f
    | symm {p q} {f g : BraidExpr α p q} : BraidRel f g → BraidRel g f
    | trans {p q} {f g h : BraidExpr α p q} : BraidRel f g → BraidRel g h → BraidRel f h
    | comp_congr {p q r q' : List α}
            {f1 f2 : BraidExpr α p q} {g1 g2 : BraidExpr α q' r}
            (h : q = q') :
            BraidRel f1 f2 → BraidRel g1 g2 →
            BraidRel (BraidExpr.comp f1 g1 h) (BraidExpr.comp f2 g2 h)
    | inv_congr {p q} {f g : BraidExpr α p q} : BraidRel f g → BraidRel (BraidExpr.inv f) (BraidExpr.inv g)
    | id_comp {p q} (f : BraidExpr α p q) :
            BraidRel (BraidExpr.comp (BraidExpr.id p) f rfl) f
    | comp_id {p q} (f : BraidExpr α p q) :
            BraidRel (BraidExpr.comp f (BraidExpr.id q) rfl) f
    | assoc {p q r s} (f : BraidExpr α p q) (g : BraidExpr α q r) (h : BraidExpr α r s) :
            BraidRel
            (BraidExpr.comp
                (BraidExpr.comp f g rfl)
                h
                rfl)
                (BraidExpr.comp f (BraidExpr.comp g h rfl) rfl)
    | inv_comp {p q} (f : BraidExpr α p q) :
            BraidRel (BraidExpr.comp f (BraidExpr.inv f) rfl) (BraidExpr.id p)
    | comp_inv {p q} (f : BraidExpr α p q) :
            BraidRel (BraidExpr.comp (BraidExpr.inv f) f rfl) (BraidExpr.id q)
    | commute (left mid right : List α) (a b c d : α) :
            BraidRel
                (BraidExpr.comp
                    (BraidExpr.gen left (mid ++ c :: d :: right) a b)
                    (BraidExpr.gen (left ++ b :: a :: mid) right c d)
                    (by
                        simpa using (swapList_assoc left mid right b a c d).symm))
                (castBraid
                    (by
                        simpa using (swapList_assoc left mid right a b c d))
                    (by
                        simpa using (swapList_assoc left mid right b a d c).symm)
                    (BraidExpr.comp
                        (BraidExpr.gen (left ++ a :: b :: mid) right c d)
                        (BraidExpr.gen left (mid ++ d :: c :: right) a b)
                        (by
                            simpa using (swapList_assoc left mid right a b d c))))
    | yang_baxter (left right : List α) (a b c : α) :
            BraidRel
                (BraidExpr.comp
                    (BraidExpr.comp
                        (BraidExpr.gen left (c :: right) a b)
                        (BraidExpr.gen (left ++ b :: []) right a c)
                        (by
                            simpa using (swapList_shift left right b a c)))
                    (BraidExpr.gen left (a :: right) b c)
                    (by
                        simpa using (swapList_shift left right b c a).symm))
                (castBraid
                    (by
                        simpa using (swapList_shift left right a b c).symm)
                    (by
                        simpa using (swapList_shift left right c b a).symm)
                    (BraidExpr.comp
                        (BraidExpr.comp
                            (BraidExpr.gen (left ++ a :: []) right b c)
                            (BraidExpr.gen left (b :: right) a c)
                            (by
                                simpa using (swapList_shift left right a c b).symm))
                        (BraidExpr.gen (left ++ c :: []) right a b)
                        (by
                            simpa using (swapList_shift left right c a b))))

def BraidGroupoid {α : Type u} (p q : List α) : Type u :=
    Quot (fun f g : BraidExpr α p q => BraidRel f g)

def braidId {α : Type u} (p : List α) : BraidGroupoid (α := α) p p :=
    Quot.mk _ (BraidExpr.id p)

def braidComp {α : Type u} {p q r : List α}
        (f : BraidGroupoid (α := α) p q) (g : BraidGroupoid (α := α) q r) :
        BraidGroupoid (α := α) p r :=
    Quot.liftOn₂ f g
        (fun f g => Quot.mk _ (BraidExpr.comp f g rfl))
        (by
            intro f1 f2 g1 hf
            apply Quot.sound
            exact BraidRel.comp_congr rfl hf (BraidRel.refl g1))
        (by
            intro f1 g1 g2 hg
            apply Quot.sound
            exact BraidRel.comp_congr rfl (BraidRel.refl f1) hg)

def braidInv {α : Type u} {p q : List α}
        (f : BraidGroupoid (α := α) p q) : BraidGroupoid (α := α) q p :=
    Quot.liftOn f
        (fun f => Quot.mk _ (BraidExpr.inv f))
        (by
            intro f1 f2 hf
            apply Quot.sound
            exact BraidRel.inv_congr hf)

instance {α : Type u} : Groupoid (List α) where
    Hom p q := BraidGroupoid (α := α) p q
    id p := braidId (α := α) p
    comp f g := braidComp (α := α) f g
    inv f := braidInv (α := α) f
    id_comp := by
        intro p q f
        refine Quot.induction_on f ?_
        intro f
        change Quot.mk _ (BraidExpr.comp (BraidExpr.id p) f rfl) = Quot.mk _ f
        apply Quot.sound
        exact BraidRel.id_comp f
    comp_id := by
        intro p q f
        refine Quot.induction_on f ?_
        intro f
        change Quot.mk _ (BraidExpr.comp f (BraidExpr.id q) rfl) = Quot.mk _ f
        apply Quot.sound
        exact BraidRel.comp_id f
    assoc := by
        intro p q r s f g h
        refine Quot.induction_on f ?_
        intro f
        refine Quot.induction_on g ?_
        intro g
        refine Quot.induction_on h ?_
        intro h
        change
          Quot.mk _ (BraidExpr.comp (BraidExpr.comp f g rfl) h rfl) =
            Quot.mk _ (BraidExpr.comp f (BraidExpr.comp g h rfl) rfl)
        apply Quot.sound
        exact BraidRel.assoc f g h
    inv_comp := by
        intro p q f
        refine Quot.induction_on f ?_
        intro f
        change
          Quot.mk _ (BraidExpr.comp (BraidExpr.inv f) f rfl) =
            Quot.mk _ (BraidExpr.id q)
        apply Quot.sound
        exact BraidRel.comp_inv f
    comp_inv := by
        intro p q f
        refine Quot.induction_on f ?_
        intro f
        change
          Quot.mk _ (BraidExpr.comp f (BraidExpr.inv f) rfl) =
            Quot.mk _ (BraidExpr.id p)
        apply Quot.sound
        exact BraidRel.inv_comp f
