import Mathlib
import LeanCategory.MonoidalWord
open CategoryTheory

/-!
# Braid groupoid

This file defines a free braided monoidal groupoid on a type of labels.
Objects are formal tensors of labels with a unit, morphisms are generated by
associators, unitors, and a braiding, and relations assert the usual monoidal
and braided coherence along with inverses.
-/

universe u

namespace BraidGroupoid

open MonoidalCategory

section Morphisms

/-- Formal braids generated by crossings, associators, and unitors. -/
inductive Hom {α : Type u} : MonoidalWord α → MonoidalWord α → Type u
    | id (X : MonoidalWord α) : Hom X X
    | α_hom (X Y Z : MonoidalWord α) : Hom ((X.tensor Y).tensor Z) (X.tensor (Y.tensor Z))
    | α_inv (X Y Z : MonoidalWord α) : Hom (X.tensor (Y.tensor Z)) ((X.tensor Y).tensor Z)
    | l_hom (X) : Hom (MonoidalWord.unit.tensor X) X
    | l_inv (X) : Hom X (MonoidalWord.unit.tensor X)
    | ρ_hom (X) : Hom (X.tensor MonoidalWord.unit) X
    | ρ_inv (X) : Hom X (X.tensor MonoidalWord.unit)
    | σ (X Y : MonoidalWord α) : Hom (X.tensor Y) (Y.tensor X)
    | σ_inv (X Y : MonoidalWord α) : Hom (Y.tensor X) (X.tensor Y)
    | comp {X Y Z} (f : Hom X Y) (g : Hom Y Z) : Hom X Z
    | whiskerLeft (X : MonoidalWord α) {Y₁ Y₂} (f : Hom Y₁ Y₂) : Hom (X.tensor Y₁) (X.tensor Y₂)
    | whiskerRight {X₁ X₂} (f : Hom X₁ X₂) (Y : MonoidalWord α) : Hom (X₁.tensor Y) (X₂.tensor Y)
    | tensor {W X Y Z} (f : Hom W Y) (g : Hom X Z) : Hom (W.tensor X) (Y.tensor Z)

scoped[ BraidGroupoid ] infixr:10 " ⟶ᵇ " => Hom
open scoped BraidGroupoid

/--
Map a braid morphism by projecting its labels with a partial function.

Labels sent to `none` are deleted at the object level.
-/
def Hom.project (map : α → Option β) : (X ⟶ᵇ Y) → (X.project map ⟶ᵇ Y.project map)
        | Hom.id X => Hom.id (X.project map)
        | Hom.α_hom X Y Z => Hom.α_hom (X.project map) (Y.project map) (Z.project map)
        | Hom.α_inv X Y Z => Hom.α_inv (X.project map) (Y.project map) (Z.project map)
        | Hom.l_hom X => Hom.l_hom (X.project map)
        | Hom.l_inv X => Hom.l_inv (X.project map)
        | Hom.ρ_hom X => Hom.ρ_hom (X.project map)
        | Hom.ρ_inv X => Hom.ρ_inv (X.project map)
        | Hom.σ X Y => Hom.σ (X.project map) (Y.project map)
        | Hom.σ_inv X Y => Hom.σ_inv (X.project map) (Y.project map)
        | Hom.comp f g => Hom.comp (f.project map) (g.project map)
        | Hom.whiskerLeft X f => Hom.whiskerLeft (X.project map) (f.project map)
        | Hom.whiskerRight f X => Hom.whiskerRight (f.project map) (X.project map)
        | Hom.tensor f g => Hom.tensor (f.project map) (g.project map)

end Morphisms

open scoped BraidGroupoid

section Relations

/-- Relations for the braid groupoid. -/
inductive HomEquiv {α : Type u} : ∀ {X Y : MonoidalWord α}, (X ⟶ᵇ Y) → (X ⟶ᵇ Y) → Prop
    | refl {X Y} (f : X ⟶ᵇ Y) : HomEquiv f f
    | symm {X Y} (f g : X ⟶ᵇ Y) : HomEquiv f g → HomEquiv g f
    | trans {X Y} {f g h : X ⟶ᵇ Y} : HomEquiv f g → HomEquiv g h → HomEquiv f h
    | comp {X Y Z} {f f' : X ⟶ᵇ Y} {g g' : Y ⟶ᵇ Z} :
            HomEquiv f f' → HomEquiv g g' → HomEquiv (f.comp g) (f'.comp g')
    | whiskerLeft (X) {Y Z} (f f' : Y ⟶ᵇ Z) :
            HomEquiv f f' → HomEquiv (f.whiskerLeft X) (f'.whiskerLeft X)
    | whiskerRight {Y Z} (f f' : Y ⟶ᵇ Z) (X) :
            HomEquiv f f' → HomEquiv (f.whiskerRight X) (f'.whiskerRight X)
    | tensor {W X Y Z} {f f' : W ⟶ᵇ X} {g g' : Y ⟶ᵇ Z} :
            HomEquiv f f' → HomEquiv g g' → HomEquiv (f.tensor g) (f'.tensor g')
    | tensorHom_def {X₁ Y₁ X₂ Y₂} (f : X₁ ⟶ᵇ Y₁) (g : X₂ ⟶ᵇ Y₂) :
            HomEquiv (f.tensor g) ((f.whiskerRight X₂).comp (g.whiskerLeft Y₁))
    | comp_id {X Y} (f : X ⟶ᵇ Y) : HomEquiv (f.comp (Hom.id _)) f
    | id_comp {X Y} (f : X ⟶ᵇ Y) : HomEquiv ((Hom.id _).comp f) f
    | assoc {X Y U V : MonoidalWord α} (f : X ⟶ᵇ U) (g : U ⟶ᵇ V) (h : V ⟶ᵇ Y) :
            HomEquiv ((f.comp g).comp h) (f.comp (g.comp h))
    | id_tensorHom_id {X Y} : HomEquiv ((Hom.id X).tensor (Hom.id Y)) (Hom.id _)
    | tensorHom_comp_tensorHom {X₁ Y₁ Z₁ X₂ Y₂ Z₂ : MonoidalWord α}
            (f₁ : X₁ ⟶ᵇ Y₁) (f₂ : X₂ ⟶ᵇ Y₂) (g₁ : Y₁ ⟶ᵇ Z₁) (g₂ : Y₂ ⟶ᵇ Z₂) :
        HomEquiv ((f₁.tensor f₂).comp (g₁.tensor g₂))
            ((f₁.comp g₁).tensor (f₂.comp g₂)) -- bifunctoriality; σ comm
    | whiskerLeft_id (X Y) : HomEquiv ((Hom.id Y).whiskerLeft X) (Hom.id (X.tensor Y))
    | id_whiskerRight (X Y) : HomEquiv ((Hom.id X).whiskerRight Y) (Hom.id (X.tensor Y))
    | α_hom_inv {X Y Z} : HomEquiv ((Hom.α_hom X Y Z).comp (Hom.α_inv X Y Z)) (Hom.id _)
    | α_inv_hom {X Y Z} : HomEquiv ((Hom.α_inv X Y Z).comp (Hom.α_hom X Y Z)) (Hom.id _)
    | associator_naturality {X₁ X₂ X₃ Y₁ Y₂ Y₃}
            (f₁ : X₁ ⟶ᵇ Y₁) (f₂ : X₂ ⟶ᵇ Y₂) (f₃ : X₃ ⟶ᵇ Y₃) :
            HomEquiv (((f₁.tensor f₂).tensor f₃).comp (Hom.α_hom Y₁ Y₂ Y₃))
                ((Hom.α_hom X₁ X₂ X₃).comp (f₁.tensor (f₂.tensor f₃)))
    | ρ_hom_inv {X} : HomEquiv ((Hom.ρ_hom X).comp (Hom.ρ_inv X)) (Hom.id _)
    | ρ_inv_hom {X} : HomEquiv ((Hom.ρ_inv X).comp (Hom.ρ_hom X)) (Hom.id _)
    | ρ_naturality {X Y} (f : X ⟶ᵇ Y) :
            HomEquiv ((f.whiskerRight MonoidalWord.unit).comp (Hom.ρ_hom Y)) ((Hom.ρ_hom X).comp f)
    | l_hom_inv {X} : HomEquiv ((Hom.l_hom X).comp (Hom.l_inv X)) (Hom.id _)
    | l_inv_hom {X} : HomEquiv ((Hom.l_inv X).comp (Hom.l_hom X)) (Hom.id _)
    | l_naturality {X Y} (f : X ⟶ᵇ Y) :
            HomEquiv ((f.whiskerLeft MonoidalWord.unit).comp (Hom.l_hom Y)) ((Hom.l_hom X).comp f)
    | pentagon {W X Y Z} :
            HomEquiv
                (((Hom.α_hom W X Y).whiskerRight Z).comp
                    ((Hom.α_hom W (X.tensor Y) Z).comp ((Hom.α_hom X Y Z).whiskerLeft W)))
                ((Hom.α_hom (W.tensor X) Y Z).comp (Hom.α_hom W X (Y.tensor Z)))
    | triangle {X Y} :
            HomEquiv ((Hom.α_hom X MonoidalWord.unit Y).comp ((Hom.l_hom Y).whiskerLeft X))
                ((Hom.ρ_hom X).whiskerRight Y)
    | σ_inv_left {X Y} : HomEquiv ((Hom.σ X Y).comp (Hom.σ_inv X Y)) (Hom.id _)
    | σ_inv_right {X Y} : HomEquiv ((Hom.σ_inv X Y).comp (Hom.σ X Y)) (Hom.id _)
    -- | σ_comm {X Y Z W} :
    --         HomEquiv
    --             (((Hom.σ X Y).whiskerRight (Z.tensor W)).comp
    --                 ((Hom.σ Z W).whiskerLeft (Y.tensor X)))
    --             (((Hom.σ Z W).whiskerLeft (X.tensor Y)).comp
    --                 ((Hom.σ X Y).whiskerRight (W.tensor Z)))
    | braiding_naturality_right {X Y Z} (f : Y ⟶ᵇ Z) :
            HomEquiv
                ((Hom.whiskerLeft X f).comp (Hom.σ X Z))
                ((Hom.σ X Y).comp (Hom.whiskerRight f X))
    | braiding_naturality_left {X Y} (f : X ⟶ᵇ Y) (Z) :
            HomEquiv
                ((Hom.whiskerRight f Z).comp (Hom.σ Y Z))
                ((Hom.σ X Z).comp (Hom.whiskerLeft Z f))
    | hexagon_forward {X Y Z} :
            HomEquiv
                ((Hom.α_hom X Y Z).comp
                    ((Hom.σ X (Y.tensor Z)).comp (Hom.α_hom Y Z X)))
                (((Hom.σ X Y).whiskerRight Z).comp
                    ((Hom.α_hom Y X Z).comp ((Hom.σ X Z).whiskerLeft Y)))
    | hexagon_reverse {X Y Z} :
            HomEquiv
                ((Hom.α_inv X Y Z).comp
                    ((Hom.σ (X.tensor Y) Z).comp (Hom.α_inv Z X Y)))
                (((Hom.σ Y Z).whiskerLeft X).comp
                    ((Hom.α_inv X Z Y).comp ((Hom.σ X Z).whiskerRight Y)))

end Relations

/--
Project braid relations along a label map.

This is the functoriality of `HomEquiv` with respect to `MonoidalWord.project`.
-/
def HomEquiv.project {α β : Type u} {X Y : MonoidalWord α} (map : α → Option β)
        {f g : X ⟶ᵇ Y} : HomEquiv f g → HomEquiv (f.project map) (g.project map) := by
    intro h
    induction h with
    | refl f => exact HomEquiv.refl _
    | symm f g h ih => exact HomEquiv.symm _ _ ih
    | trans hfg hgh ihfg ihgh => exact HomEquiv.trans ihfg ihgh
    | comp hf hg ihf ihg => exact HomEquiv.comp ihf ihg
    | whiskerLeft X f f' hf ih => exact HomEquiv.whiskerLeft _ _ _ ih
    | whiskerRight f f' X hf ih => exact HomEquiv.whiskerRight _ _ _ ih
    | tensor hf hg ihf ihg => exact HomEquiv.tensor ihf ihg
    | tensorHom_def f g => exact HomEquiv.tensorHom_def (f.project map) (g.project map)
    | comp_id f => exact HomEquiv.comp_id (f.project map)
    | id_comp f => exact HomEquiv.id_comp (f.project map)
    | assoc f g h => exact HomEquiv.assoc (f.project map) (g.project map) (h.project map)
    | id_tensorHom_id => exact HomEquiv.id_tensorHom_id
    | tensorHom_comp_tensorHom f₁ f₂ g₁ g₂ =>
        exact HomEquiv.tensorHom_comp_tensorHom (f₁.project map) (f₂.project map)
            (g₁.project map) (g₂.project map)
    | whiskerLeft_id X Y => exact HomEquiv.whiskerLeft_id (X.project map) (Y.project map)
    | id_whiskerRight X Y => exact HomEquiv.id_whiskerRight (X.project map) (Y.project map)
    | α_hom_inv => exact HomEquiv.α_hom_inv
    | α_inv_hom => exact HomEquiv.α_inv_hom
    | associator_naturality f₁ f₂ f₃ =>
        exact HomEquiv.associator_naturality (f₁.project map) (f₂.project map) (f₃.project map)
    | ρ_hom_inv => exact HomEquiv.ρ_hom_inv
    | ρ_inv_hom => exact HomEquiv.ρ_inv_hom
    | ρ_naturality f => exact HomEquiv.ρ_naturality (f.project map)
    | l_hom_inv => exact HomEquiv.l_hom_inv
    | l_inv_hom => exact HomEquiv.l_inv_hom
    | l_naturality f => exact HomEquiv.l_naturality (f.project map)
    | pentagon => exact HomEquiv.pentagon
    | triangle => exact HomEquiv.triangle
    | σ_inv_left => exact HomEquiv.σ_inv_left
    | σ_inv_right => exact HomEquiv.σ_inv_right
    | braiding_naturality_right f =>
        exact HomEquiv.braiding_naturality_right (f.project map)
    | braiding_naturality_left f Z =>
        exact HomEquiv.braiding_naturality_left (f.project map) (Z.project map)
    | hexagon_forward => exact HomEquiv.hexagon_forward
    | hexagon_reverse => exact HomEquiv.hexagon_reverse

section Instances

/-- Setoid for braid morphisms. -/
def setoidHom {α : Type u} (X Y : MonoidalWord α) : Setoid (X ⟶ᵇ Y) :=
    ⟨HomEquiv, ⟨HomEquiv.refl, HomEquiv.symm _ _, HomEquiv.trans⟩⟩

section BraidInstance -- so "open HomEquiv" doesn't pollute outside

open HomEquiv

/-- The category structure on `MonoidalWord`, quotienting by braid relations. -/
instance (α : Type u) : Category.{u} (MonoidalWord α) where
    Hom X Y := Quotient (BraidGroupoid.setoidHom X Y)
    id X := ⟦Hom.id X⟧
    comp := Quotient.map₂ Hom.comp (fun _ _ hf _ _ hg ↦ HomEquiv.comp hf hg)
    id_comp := by
        rintro X Y ⟨f⟩
        exact Quotient.sound (id_comp f)
    comp_id := by
        rintro X Y ⟨f⟩
        exact Quotient.sound (comp_id f)
    assoc := by
        rintro W X Y Z ⟨f⟩ ⟨g⟩ ⟨h⟩
        exact Quotient.sound (assoc f g h)

/-- The monoidal structure induced by formal tensoring of words and morphisms. -/
instance (α : Type u) : MonoidalCategory (MonoidalWord α) where
    tensorObj X Y := MonoidalWord.tensor X Y
    tensorHom := Quotient.map₂ Hom.tensor (fun _ _ hf _ _ hg ↦ HomEquiv.tensor hf hg)
    whiskerLeft X _ _ f :=
        Quot.map (fun f ↦ Hom.whiskerLeft X f) (fun f f' ↦ .whiskerLeft X f f') f
    whiskerRight f Y :=
        Quot.map (fun f ↦ Hom.whiskerRight f Y) (fun f f' ↦ .whiskerRight f f' Y) f
    tensorHom_def {W X Y Z} := by
        rintro ⟨f⟩ ⟨g⟩
        exact Quotient.sound (tensorHom_def _ _)
    id_tensorHom_id _ _ := Quot.sound id_tensorHom_id
    tensorHom_comp_tensorHom {X₁ Y₁ Z₁ X₂ Y₂ Z₂} := by
        rintro ⟨f₁⟩ ⟨f₂⟩ ⟨g₁⟩ ⟨g₂⟩
        exact Quotient.sound (tensorHom_comp_tensorHom _ _ _ _)
    whiskerLeft_id X Y := Quot.sound (HomEquiv.whiskerLeft_id X Y)
    id_whiskerRight X Y := Quot.sound (HomEquiv.id_whiskerRight X Y)
    tensorUnit := MonoidalWord.unit
    associator X Y Z :=
        ⟨⟦Hom.α_hom X Y Z⟧, ⟦Hom.α_inv X Y Z⟧, Quotient.sound α_hom_inv,
            Quotient.sound α_inv_hom⟩
    associator_naturality {X₁ X₂ X₃ Y₁ Y₂ Y₃} := by
        rintro ⟨f₁⟩ ⟨f₂⟩ ⟨f₃⟩
        exact Quotient.sound (associator_naturality _ _ _)
    leftUnitor X :=
        ⟨⟦Hom.l_hom X⟧, ⟦Hom.l_inv X⟧, Quotient.sound l_hom_inv,
            Quotient.sound l_inv_hom⟩
    leftUnitor_naturality {X Y} := by
        rintro ⟨f⟩
        exact Quotient.sound (l_naturality _)
    rightUnitor X :=
        ⟨⟦Hom.ρ_hom X⟧, ⟦Hom.ρ_inv X⟧, Quotient.sound ρ_hom_inv,
            Quotient.sound ρ_inv_hom⟩
    rightUnitor_naturality {X Y} := by
        rintro ⟨f⟩
        exact Quotient.sound (ρ_naturality _)
    pentagon _ _ _ _ := Quotient.sound pentagon
    triangle _ _ := Quotient.sound triangle

/-- The braided structure coming from the formal crossing generators. -/
instance (α : Type u) : BraidedCategory (MonoidalWord α) where
    braiding X Y :=
        ⟨⟦Hom.σ X Y⟧, ⟦Hom.σ_inv X Y⟧,
            Quotient.sound σ_inv_left, Quotient.sound σ_inv_right⟩
    braiding_naturality_right := by
        rintro X Y Z ⟨f⟩
        exact Quotient.sound (HomEquiv.braiding_naturality_right f)
    braiding_naturality_left := by
        rintro X Y ⟨f⟩ Z
        exact Quotient.sound (HomEquiv.braiding_naturality_left f Z)
    hexagon_forward := by
        intro X Y Z
        exact Quotient.sound (HomEquiv.hexagon_forward (X := X) (Y := Y) (Z := Z))
    hexagon_reverse := by
        intro X Y Z
        exact Quotient.sound (HomEquiv.hexagon_reverse (X := X) (Y := Y) (Z := Z))

end BraidInstance

end Instances

/-! ## Helper lemmas -/

/-- Quotient computation for composition. -/
@[simp]
theorem mk_comp {α : Type u} {X Y Z : MonoidalWord α} (f : Hom X Y) (g : Hom Y Z) :
        ⟦f.comp g⟧ = @CategoryStruct.comp (MonoidalWord α) _ _ _ _ ⟦f⟧ ⟦g⟧ :=
  rfl

/-- Quotient computation for tensoring morphisms. -/
@[simp]
theorem mk_tensor {α : Type u} {X₁ Y₁ X₂ Y₂ : MonoidalWord α} (f : Hom X₁ Y₁) (g : Hom X₂ Y₂) :
        ⟦f.tensor g⟧ = @MonoidalCategory.tensorHom (MonoidalWord α) _ _ _ _ _ _ ⟦f⟧ ⟦g⟧ :=
  rfl

/-- Quotient computation for left whiskering. -/
@[simp]
theorem mk_whiskerLeft {α : Type u} (X : MonoidalWord α) {Y₁ Y₂ : MonoidalWord α} (f : Hom Y₁ Y₂) :
        ⟦f.whiskerLeft X⟧ =
            MonoidalCategory.whiskerLeft (C := MonoidalWord α) (X := X) (f := ⟦f⟧) :=
  rfl

/-- Quotient computation for right whiskering. -/
@[simp]
theorem mk_whiskerRight {α : Type u} {X₁ X₂ : MonoidalWord α} (f : Hom X₁ X₂) (Y : MonoidalWord α) :
        ⟦f.whiskerRight Y⟧ =
            MonoidalCategory.whiskerRight (C := MonoidalWord α) (f := ⟦f⟧) (Y := Y) :=
  rfl

/-- Quotient computation for identities. -/
@[simp]
theorem mk_id {α : Type u} {X : MonoidalWord α} : ⟦Hom.id X⟧ = 𝟙 X :=
  rfl

/-- Quotient computation for associators. -/
@[simp]
theorem mk_α_hom {α : Type u} {X Y Z : MonoidalWord α} : ⟦Hom.α_hom X Y Z⟧ = (α_ X Y Z).hom :=
  rfl

/-- Quotient computation for inverse associators. -/
@[simp]
theorem mk_α_inv {α : Type u} {X Y Z : MonoidalWord α} : ⟦Hom.α_inv X Y Z⟧ = (α_ X Y Z).inv :=
  rfl

/-- Quotient computation for right unitor. -/
@[simp]
theorem mk_ρ_hom {α : Type u} {X : MonoidalWord α} : ⟦Hom.ρ_hom X⟧ = (ρ_ X).hom :=
  rfl

/-- Quotient computation for inverse right unitor. -/
@[simp]
theorem mk_ρ_inv {α : Type u} {X : MonoidalWord α} : ⟦Hom.ρ_inv X⟧ = (ρ_ X).inv :=
  rfl

/-- Quotient computation for left unitor. -/
@[simp]
theorem mk_l_hom {α : Type u} {X : MonoidalWord α} : ⟦Hom.l_hom X⟧ = (λ_ X).hom :=
  rfl

/-- Quotient computation for inverse left unitor. -/
@[simp]
theorem mk_l_inv {α : Type u} {X : MonoidalWord α} : ⟦Hom.l_inv X⟧ = (λ_ X).inv :=
    rfl

/-- Quotient computation for the braiding. -/
@[simp]
theorem mk_σ {α : Type u} {X Y : MonoidalWord α} :
        (⟦Hom.σ X Y⟧ : (X ⊗ Y) ⟶ (Y ⊗ X)) = (β_ X Y).hom :=
    rfl

/-- Quotient computation for the inverse braiding. -/
@[simp]
theorem mk_σ_inv {α : Type u} {X Y : MonoidalWord α} :
        (⟦Hom.σ_inv X Y⟧ : (Y ⊗ X) ⟶ (X ⊗ Y)) = (β_ X Y).inv :=
  rfl

/--
The abbreviation for `⟦f⟧` as a morphism.

This avoids the coercion ambiguity of `⟦f⟧` when used with category structure.
-/
abbrev homMk {α : Type u} {X Y : MonoidalWord α} (f : Hom X Y) : X ⟶ Y := ⟦f⟧


/--
Induction principle for morphisms in the quotient category.

This allows proofs by induction on the underlying formal morphism.
-/
theorem Hom.inductionOn {α : Type u}
        {motive : {X Y : MonoidalWord α} → (X ⟶ Y) → Prop} {X Y : MonoidalWord α} (t : X ⟶ Y)
        (id : (X : MonoidalWord α) → motive (𝟙 X))
        (α_hom : (X Y Z : MonoidalWord α) → motive (α_ X Y Z).hom)
        (α_inv : (X Y Z : MonoidalWord α) → motive (α_ X Y Z).inv)
        (l_hom : (X : MonoidalWord α) → motive (λ_ X).hom)
        (l_inv : (X : MonoidalWord α) → motive (λ_ X).inv)
        (ρ_hom : (X : MonoidalWord α) → motive (ρ_ X).hom)
        (ρ_inv : (X : MonoidalWord α) → motive (ρ_ X).inv)
        (σ_hom : (X Y : MonoidalWord α) → motive (⟦Hom.σ X Y⟧))
        (σ_inv : (X Y : MonoidalWord α) → motive (⟦Hom.σ_inv X Y⟧))
        (comp : {X Y Z : MonoidalWord α} → (f : X ⟶ Y) → (g : Y ⟶ Z) →
            motive f → motive g → motive (f ≫ g))
        (whiskerLeft : {Y Z : MonoidalWord α} → (X : MonoidalWord α) → (f : Y ⟶ Z) →
            motive f → motive (X ◁ f))
        (whiskerRight : {X Y : MonoidalWord α} → (f : X ⟶ Y) → (Z : MonoidalWord α) →
            motive f → motive (f ▷ Z)) :
        motive t := by
    apply Quotient.inductionOn
    intro f
    induction f with
    | id X => exact id X
    | α_hom X Y Z => exact α_hom X Y Z
    | α_inv X Y Z => exact α_inv X Y Z
    | l_hom X => exact l_hom X
    | l_inv X => exact l_inv X
    | ρ_hom X => exact ρ_hom X
    | ρ_inv X => exact ρ_inv X
    | σ X Y => exact σ_hom X Y
    | σ_inv X Y => exact σ_inv X Y
    | comp f g hf hg => exact comp _ _ (hf ⟦f⟧) (hg ⟦g⟧)
    | whiskerLeft X f hf => exact whiskerLeft X _ (hf ⟦f⟧)
    | whiskerRight f X hf => exact whiskerRight _ X (hf ⟦f⟧)
    | @tensor W X Y Z f g hf hg =>
            have : homMk f ⊗ₘ homMk g = homMk f ▷ X ≫ Y ◁ homMk g :=
                Quotient.sound (HomEquiv.tensorHom_def f g)
            change motive (homMk f ⊗ₘ homMk g)
            rw [this]
            exact comp _ _ (whiskerRight _ _ (hf ⟦f⟧)) (whiskerLeft _ _ (hg ⟦g⟧))

/-- Every morphism in the braid groupoid is an isomorphism. -/
theorem isIso_quot {α : Type u} {X Y : MonoidalWord α} (f : X ⟶ Y) : IsIso f := by
    refine Hom.inductionOn (α := α) (t := f)
        (id := fun X => by simpa using (inferInstance : IsIso (𝟙 X)))
        (α_hom := fun X Y Z => by
            simpa using (inferInstance : IsIso (α_ X Y Z).hom))
        (α_inv := fun X Y Z => by
            simpa using (inferInstance : IsIso (α_ X Y Z).inv))
        (l_hom := fun X => by
            simpa using (inferInstance : IsIso (λ_ X).hom))
        (l_inv := fun X => by
            simpa using (inferInstance : IsIso (λ_ X).inv))
        (ρ_hom := fun X => by
            simpa using (inferInstance : IsIso (ρ_ X).hom))
        (ρ_inv := fun X => by
            simpa using (inferInstance : IsIso (ρ_ X).inv))
        (σ_hom := fun X Y => by
            simpa [mk_σ] using (inferInstance : IsIso (β_ X Y).hom))
        (σ_inv := fun X Y => by
            simpa [mk_σ_inv] using (inferInstance : IsIso (β_ X Y).inv))
        (comp := fun f g hf hg ↦ by
            simpa using (inferInstance : IsIso (f ≫ g)))
        (whiskerLeft := fun X f hf => by
            simpa using (inferInstance : IsIso (X ◁ f)))
        (whiskerRight := fun f Z hf ↦ by
            simpa using (inferInstance : IsIso (f ▷ Z)))

/-- The braid groupoid instance on `MonoidalWord`. -/
noncomputable instance (α : Type u) : Groupoid (MonoidalWord α) :=
    Groupoid.ofIsIso (C := MonoidalWord α) (fun f => isIso_quot (α := α) f)

/-- A shorthand class for braided monoidal groupoids. -/
class BraidedGroupoid (C : Type u) [Category C] [MonoidalCategory C]
    [BraidedCategory C] [Groupoid C]

/-- The free braided monoidal groupoid on a type of labels. -/
instance (α : Type u) : BraidedGroupoid (MonoidalWord α) where
end BraidGroupoid
