import Mathlib
open CategoryTheory

/-
\begin{definition}[Braid groupoid, $\T$]
\label{def:T}
 $\T$ is the \textit{braid groupoid}. Informally,
 it represents braids from the braid group where
 each strand is labeled; two braids can compose
 only when their labels line up.

 Its objects are sequences of \textit{distinct} letters, where
 each letter labels a strand. This is a slight modification of $\K{}$'s
 objects, which allow duplicate letters. Because $\K{}$'s
 object monoid is free, we can
 easily rename strands to make a distinct sequence
 to represent some braid from $\K{}$ in $\T{}.$
 % The first and last
 % braids in Figure~\ref{fig:braid-canon-example} are
 % equivalent words in $\T{}.$
 We often label strands by which box they connect
 to and index them by their total order from
 that box.


$\T{}$'s morphisms are generated by
crossings of two strands.
For any
$\alpha, \beta$ that are
possibly empty sequences of distinct letters
not containing the
letters $c, d,$ there is a generator
$\gen{c}{d}{} : \alpha{}cd\beta
\to \alpha{}dc\beta$
that crosses strand $c$ over strand $d.$ $\gen{c}{d}{p}$
is defined for any sequence $p$ where
$c$ is directly to the left of $d.$ See
Figure~\ref{fig:T-gen}
for an example of $\gen{c}{d}{} : \alpha{}cd\beta
\to \alpha{}dc\beta.$
In the notation of $\K{},$ we would write
$\gen{c}{d}{} : \alpha{}cd\beta
\to \alpha{}dc\beta$ as
$\id{}_{\alpha} \otimes \sigma_{[c],[d]} \otimes \id{}_{\beta}.$

% \begin{figure}[h]
%     \centering
%     \includegraphics[width=0.5\linewidth]{figs_not_from_python/alpha-x-y-beta.pdf}
%     \caption{Diagrammatic
%     representation of $\gen{c}{d}{} : \alpha{}cd\beta \to \alpha{}dc\beta$
%     for $|\alpha| = 3, |\beta|=5.$
%     The strands in $\alpha, \beta$ do not move,
%     and only $c, d$ cross.}
%     \label{fig:T-gen}
% \end{figure}

Note that the domain and the crossed strands $c, d$ uniquely
determine the codomain. Hence
for some sequence of strands $p$ that contains $[c, d],$
we can describe a
unique generator $\gen{c}{d}{p}.$
When context allows, we omit the object
$p$ and refer to some class of generators
$\gen{c}{d}{},$ which all cross $c$ over
$d$ but differ in the strands to the left
and right of $c, d.$
The identity braid (no crossings)
for any sequence object
$p$ is denoted as $\id{}_p : p \to p$.  Similarly, we denote
an identity morphism, regardless of object, with
$\id{}.$

 $\T$ has commutative diagrams
 (the category-theoretic analog of the
 equations in the presentation of a
 group) for
 the shift-past commuting relation
 $$
  \gen{a}{b}{} ; \gen{c}{d}{}
  =
  \gen{c}{d}{} ; \gen{a}{b}{}
 $$
 and the Yang-Baxter equation
 $$
  \gen{a}{b}{}
  ; \gen{a}{c}{}
  ; \gen{b}{c}{}
  =
  \gen{b}{c}{}
  ; \gen{a}{c}{}
  ; \gen{a}{b}{},
 $$ where $a,b,c,d$ are distinct in both. These relations correspond to diagram moves \Btwo{} and
 \Bthree{} respectively, and \Bone{} arises from
 every braid being invertible.
 \end{definition}
-/

-- Implement the braid groupoid. You should follow the same structure
-- as in FreeMonoidal.lean: define the object monoid for a generic type α,
-- then the morphisms, then the commutative diagrams. Because this is the
-- braid groupoid, the extra morphisms will be the σ crossings and inverses,
-- and extra commutative diagrams will be for the commuting, yang-baxter, and
-- inverses. Then provide a named instance of Category, then of MonoidalCategory.

universe u

namespace BraidGroupoid

open MonoidalCategory

-- set_option genSizeOfSpec false in
-- set_option genInjectivity false in
/-- Objects for the braid groupoid: formal tensors of letters with a unit. -/
-- TODO twisted involutive
inductive Monoid (α : Type u) : Type u
  | of : α → Monoid α
  | unit : Monoid α
  | tensor : Monoid α → Monoid α → Monoid α
  deriving Inhabited, Repr

-- true whenever structures match (not just same length!)
-- @[simp]
-- def Monoid.match : Monoid α → Monoid β → Prop
--   | Monoid.of _, Monoid.of _ => True
--   | Monoid.unit, Monoid.unit => True
--   | Monoid.tensor x₁ y₁, Monoid.tensor x₂ y₂ => x₁.match x₂ ∧ y₁.match y₂
--   | _, _ => False

-- def Monoid.Match (β : Type u) : Monoid α → Type u
--   | Monoid.of _ => β
--   | Monoid.unit => PUnit
--   | Monoid.tensor x y => Monoid.Match β x × Monoid.Match β y

inductive Monoid.Match (β : Type u) : Monoid α → Type u
  | unit : Monoid.Match β .unit
  | of : β → Monoid.Match β (.of X)
  | tensor : Monoid.Match β X → Monoid.Match β Y → Monoid.Match β (.tensor X Y)
  -- | Monoid.of _ => β
  -- | Monoid.unit => PUnit
  -- | Monoid.unit, Monoid.unit => True
  -- | Monoid.tensor x₁ y₁, Monoid.tensor x₂ y₂ => x₁.match x₂ ∧ y₁.match y₂
  -- | _, _ => False

def Monoid.Match.toMonoid : Monoid.Match β X → Monoid β
  | unit => .unit
  | of b => .of b
  | tensor mx my => .tensor mx.toMonoid my.toMonoid

def Monoid.project (f : α → Option β) : Monoid α → Monoid β
  | Monoid.unit => .unit
  | Monoid.of a => match f a with
      | some b => .of b
      | none => .unit
  | Monoid.tensor x y => .tensor (x.project f) (y.project f)

  -- match X with
  -- | Monoid.of _ => .of m
  -- | Monoid.unit => .unit
  -- | Monoid.tensor _ _ =>
  --     let (mx, my) := m
  --     .tensor (Monoid.Match.toMonoid mx) (Monoid.Match.toMonoid my)

/-- Formal braids generated by crossings, associators, and unitors. -/
inductive Hom {α : Type u} : Monoid α → Monoid α → Type u
    | id (X : Monoid α) : Hom X X
    | α_hom (X Y Z : Monoid α) : Hom ((X.tensor Y).tensor Z) (X.tensor (Y.tensor Z))
    | α_inv (X Y Z : Monoid α) : Hom (X.tensor (Y.tensor Z)) ((X.tensor Y).tensor Z)
    | l_hom (X) : Hom (Monoid.unit.tensor X) X
    | l_inv (X) : Hom X (Monoid.unit.tensor X)
    | ρ_hom (X) : Hom (X.tensor Monoid.unit) X
    | ρ_inv (X) : Hom X (X.tensor Monoid.unit)
    | σ (X Y : Monoid α) : Hom (X.tensor Y) (Y.tensor X)
    | σ_inv (X Y : Monoid α) : Hom (Y.tensor X) (X.tensor Y)
    | comp {X Y Z} (f : Hom X Y) (g : Hom Y Z) : Hom X Z
    | whiskerLeft (X : Monoid α) {Y₁ Y₂} (f : Hom Y₁ Y₂) : Hom (X.tensor Y₁) (X.tensor Y₂)
    | whiskerRight {X₁ X₂} (f : Hom X₁ X₂) (Y : Monoid α) : Hom (X₁.tensor Y) (X₂.tensor Y)
    | tensor {W X Y Z} (f : Hom W Y) (g : Hom X Z) : Hom (W.tensor X) (Y.tensor Z)

local infixr:10 " ⟶ᵇ " => Hom

def Hom.newMatch {α β : Type u} {X Y : Monoid α} : (X ⟶ᵇ Y) → (X.Match β) → Y.Match β
    | Hom.id _, A => A
    | Hom.α_hom X Y Z, .tensor (.tensor A B) C => .tensor A (.tensor B C)
    | Hom.α_inv X Y Z, .tensor A (.tensor B C) => .tensor (.tensor A B) C
    | Hom.l_hom X, .tensor .unit A => A
    | Hom.l_inv X, A => .tensor .unit A
    | Hom.ρ_hom X, .tensor A .unit => A
    | Hom.ρ_inv X, A => .tensor A .unit
    | Hom.σ X Y, .tensor A B => .tensor B A
    | Hom.σ_inv X Y, .tensor B A => .tensor A B
    | Hom.comp f g, A => Hom.newMatch g (Hom.newMatch f A)
    | Hom.whiskerLeft X f, .tensor A B => .tensor A (Hom.newMatch f B)
    | Hom.whiskerRight f X, .tensor A B => .tensor (Hom.newMatch f A) B
    | Hom.tensor f g, .tensor A B => .tensor (Hom.newMatch f A) (Hom.newMatch g B)

def Hom.newCod {α β : Type u} {X Y : Monoid α} : (X ⟶ᵇ Y) → (X.Match β) → Monoid β
    | f, A => (Hom.newMatch f A).toMonoid

def Hom.enrich : (f : X ⟶ᵇ Y) → (A : X.Match β) → (A.toMonoid ⟶ᵇ f.newCod A)
    | Hom.id X, A => Hom.id (A.toMonoid)
    | Hom.α_hom X Y Z, .tensor (.tensor A B) C => Hom.α_hom A.toMonoid B.toMonoid C.toMonoid
    | Hom.α_inv X Y Z, .tensor A (.tensor B C) => Hom.α_inv A.toMonoid B.toMonoid C.toMonoid
    | Hom.l_hom X, .tensor .unit A => Hom.l_hom A.toMonoid
    | Hom.l_inv X, A => Hom.l_inv A.toMonoid
    | Hom.ρ_hom X, .tensor A .unit => Hom.ρ_hom A.toMonoid
    | Hom.ρ_inv X, A => Hom.ρ_inv A.toMonoid
    | Hom.σ X Y, .tensor A B => Hom.σ A.toMonoid B.toMonoid
    | Hom.σ_inv X Y, .tensor B A => Hom.σ_inv A.toMonoid B.toMonoid
    | Hom.comp f g, A => Hom.comp (Hom.enrich f A) (Hom.enrich g (Hom.newMatch f A))
    | Hom.whiskerLeft X f, .tensor A B => Hom.whiskerLeft A.toMonoid (Hom.enrich f B)
    | Hom.whiskerRight f X, .tensor A B => Hom.whiskerRight (Hom.enrich f A) B.toMonoid
    | Hom.tensor f g, .tensor A B => Hom.tensor (Hom.enrich f A) (Hom.enrich g B)

def Hom.project (map : α → Option β) : (X ⟶ᵇ Y) → (X.project map ⟶ᵇ Y.project map)
  | Hom.id X => Hom.id (X.project map)
  | Hom.α_hom X Y Z => Hom.α_hom (X.project map) (Y.project map) (Z.project map)
  | Hom.α_inv X Y Z => Hom.α_inv (X.project map) (Y.project map) (Z.project map)
  | Hom.l_hom X => Hom.l_hom (X.project map)
  | Hom.l_inv X => Hom.l_inv (X.project map)
  | Hom.ρ_hom X => Hom.ρ_hom (X.project map)
  | Hom.ρ_inv X => Hom.ρ_inv (X.project map)
  | Hom.σ X Y => Hom.σ (X.project map) (Y.project map)
  | Hom.σ_inv X Y => Hom.σ_inv (X.project map) (Y.project map)
  | Hom.comp f g => Hom.comp (f.project map) (g.project map)
  | Hom.whiskerLeft X f => Hom.whiskerLeft (X.project map) (f.project map)
  | Hom.whiskerRight f X => Hom.whiskerRight (f.project map) (X.project map)
  | Hom.tensor f g => Hom.tensor (f.project map) (g.project map)

-- /-- Formal inverse on generators, reversing composition. -/
-- def Hom.inv {α : Type u} {X Y : Monoid α} : Hom X Y → Hom Y X
--     | Hom.id X => Hom.id X
--     | Hom.α_hom X Y Z => Hom.α_inv X Y Z
--     | Hom.α_inv X Y Z => Hom.α_hom X Y Z
--     | Hom.l_hom X => Hom.l_inv X
--     | Hom.l_inv X => Hom.l_hom X
--     | Hom.ρ_hom X => Hom.ρ_inv X
--     | Hom.ρ_inv X => Hom.ρ_hom X
--     | Hom.σ X Y => Hom.σ_inv X Y
--     | Hom.σ_inv X Y => Hom.σ X Y
--     | Hom.comp f g => Hom.comp g.inv f.inv
--     | Hom.whiskerLeft X f => Hom.whiskerLeft X f.inv
--     | Hom.whiskerRight f X => Hom.whiskerRight f.inv X
--     | Hom.tensor f g => Hom.tensor f.inv g.inv

/-- Relations for the braid groupoid. -/
inductive HomEquiv {α : Type u} : ∀ {X Y : Monoid α}, (X ⟶ᵇ Y) → (X ⟶ᵇ Y) → Prop
    | refl {X Y} (f : X ⟶ᵇ Y) : HomEquiv f f
    | symm {X Y} (f g : X ⟶ᵇ Y) : HomEquiv f g → HomEquiv g f
    | trans {X Y} {f g h : X ⟶ᵇ Y} : HomEquiv f g → HomEquiv g h → HomEquiv f h
    | comp {X Y Z} {f f' : X ⟶ᵇ Y} {g g' : Y ⟶ᵇ Z} :
            HomEquiv f f' → HomEquiv g g' → HomEquiv (f.comp g) (f'.comp g')
    | whiskerLeft (X) {Y Z} (f f' : Y ⟶ᵇ Z) :
            HomEquiv f f' → HomEquiv (f.whiskerLeft X) (f'.whiskerLeft X)
    | whiskerRight {Y Z} (f f' : Y ⟶ᵇ Z) (X) :
            HomEquiv f f' → HomEquiv (f.whiskerRight X) (f'.whiskerRight X)
    | tensor {W X Y Z} {f f' : W ⟶ᵇ X} {g g' : Y ⟶ᵇ Z} :
            HomEquiv f f' → HomEquiv g g' → HomEquiv (f.tensor g) (f'.tensor g')
    | tensorHom_def {X₁ Y₁ X₂ Y₂} (f : X₁ ⟶ᵇ Y₁) (g : X₂ ⟶ᵇ Y₂) :
            HomEquiv (f.tensor g) ((f.whiskerRight X₂).comp (g.whiskerLeft Y₁))
    | comp_id {X Y} (f : X ⟶ᵇ Y) : HomEquiv (f.comp (Hom.id _)) f
    | id_comp {X Y} (f : X ⟶ᵇ Y) : HomEquiv ((Hom.id _).comp f) f
    | assoc {X Y U V : Monoid α} (f : X ⟶ᵇ U) (g : U ⟶ᵇ V) (h : V ⟶ᵇ Y) :
            HomEquiv ((f.comp g).comp h) (f.comp (g.comp h))
    | id_tensorHom_id {X Y} : HomEquiv ((Hom.id X).tensor (Hom.id Y)) (Hom.id _)
    | tensorHom_comp_tensorHom {X₁ Y₁ Z₁ X₂ Y₂ Z₂ : Monoid α}
            (f₁ : X₁ ⟶ᵇ Y₁) (f₂ : X₂ ⟶ᵇ Y₂) (g₁ : Y₁ ⟶ᵇ Z₁) (g₂ : Y₂ ⟶ᵇ Z₂) :
        HomEquiv ((f₁.tensor f₂).comp (g₁.tensor g₂))
            ((f₁.comp g₁).tensor (f₂.comp g₂)) -- bifunctoriality; σ comm
    | whiskerLeft_id (X Y) : HomEquiv ((Hom.id Y).whiskerLeft X) (Hom.id (X.tensor Y))
    | id_whiskerRight (X Y) : HomEquiv ((Hom.id X).whiskerRight Y) (Hom.id (X.tensor Y))
    | α_hom_inv {X Y Z} : HomEquiv ((Hom.α_hom X Y Z).comp (Hom.α_inv X Y Z)) (Hom.id _)
    | α_inv_hom {X Y Z} : HomEquiv ((Hom.α_inv X Y Z).comp (Hom.α_hom X Y Z)) (Hom.id _)
    | associator_naturality {X₁ X₂ X₃ Y₁ Y₂ Y₃}
            (f₁ : X₁ ⟶ᵇ Y₁) (f₂ : X₂ ⟶ᵇ Y₂) (f₃ : X₃ ⟶ᵇ Y₃) :
            HomEquiv (((f₁.tensor f₂).tensor f₃).comp (Hom.α_hom Y₁ Y₂ Y₃))
                ((Hom.α_hom X₁ X₂ X₃).comp (f₁.tensor (f₂.tensor f₃)))
    | ρ_hom_inv {X} : HomEquiv ((Hom.ρ_hom X).comp (Hom.ρ_inv X)) (Hom.id _)
    | ρ_inv_hom {X} : HomEquiv ((Hom.ρ_inv X).comp (Hom.ρ_hom X)) (Hom.id _)
    | ρ_naturality {X Y} (f : X ⟶ᵇ Y) :
            HomEquiv ((f.whiskerRight Monoid.unit).comp (Hom.ρ_hom Y)) ((Hom.ρ_hom X).comp f)
    | l_hom_inv {X} : HomEquiv ((Hom.l_hom X).comp (Hom.l_inv X)) (Hom.id _)
    | l_inv_hom {X} : HomEquiv ((Hom.l_inv X).comp (Hom.l_hom X)) (Hom.id _)
    | l_naturality {X Y} (f : X ⟶ᵇ Y) :
            HomEquiv ((f.whiskerLeft Monoid.unit).comp (Hom.l_hom Y)) ((Hom.l_hom X).comp f)
    | pentagon {W X Y Z} :
            HomEquiv
                (((Hom.α_hom W X Y).whiskerRight Z).comp
                    ((Hom.α_hom W (X.tensor Y) Z).comp ((Hom.α_hom X Y Z).whiskerLeft W)))
                ((Hom.α_hom (W.tensor X) Y Z).comp (Hom.α_hom W X (Y.tensor Z)))
    | triangle {X Y} :
            HomEquiv ((Hom.α_hom X Monoid.unit Y).comp ((Hom.l_hom Y).whiskerLeft X))
                ((Hom.ρ_hom X).whiskerRight Y)
    | σ_inv_left {X Y} : HomEquiv ((Hom.σ X Y).comp (Hom.σ_inv X Y)) (Hom.id _)
    | σ_inv_right {X Y} : HomEquiv ((Hom.σ_inv X Y).comp (Hom.σ X Y)) (Hom.id _)
    -- | σ_comm {X Y Z W} :
    --         HomEquiv
    --             (((Hom.σ X Y).whiskerRight (Z.tensor W)).comp
    --                 ((Hom.σ Z W).whiskerLeft (Y.tensor X)))
    --             (((Hom.σ Z W).whiskerLeft (X.tensor Y)).comp
    --                 ((Hom.σ X Y).whiskerRight (W.tensor Z)))
    | braiding_naturality_right {X Y Z} (f : Y ⟶ᵇ Z) :
            HomEquiv
                ((Hom.whiskerLeft X f).comp (Hom.σ X Z))
                ((Hom.σ X Y).comp (Hom.whiskerRight f X))
    | braiding_naturality_left {X Y} (f : X ⟶ᵇ Y) (Z) :
            HomEquiv
                ((Hom.whiskerRight f Z).comp (Hom.σ Y Z))
                ((Hom.σ X Z).comp (Hom.whiskerLeft Z f))
    | hexagon_forward {X Y Z} :
            HomEquiv
                ((Hom.α_hom X Y Z).comp
                    ((Hom.σ X (Y.tensor Z)).comp (Hom.α_hom Y Z X)))
                (((Hom.σ X Y).whiskerRight Z).comp
                    ((Hom.α_hom Y X Z).comp ((Hom.σ X Z).whiskerLeft Y)))
    | hexagon_reverse {X Y Z} :
            HomEquiv
                ((Hom.α_inv X Y Z).comp
                    ((Hom.σ (X.tensor Y) Z).comp (Hom.α_inv Z X Y)))
                (((Hom.σ Y Z).whiskerLeft X).comp
                    ((Hom.α_inv X Z Y).comp ((Hom.σ X Z).whiskerRight Y)))

def HomEquiv.project {α β : Type u} {X Y : Monoid α} (map : α → Option β)
        {f g : X ⟶ᵇ Y} : HomEquiv f g → HomEquiv (f.project map) (g.project map) := by
    intro h
    induction h with
    | refl f => exact HomEquiv.refl _
    | symm f g h ih => exact HomEquiv.symm _ _ ih
    | trans hfg hgh ihfg ihgh => exact HomEquiv.trans ihfg ihgh
    | comp hf hg ihf ihg => exact HomEquiv.comp ihf ihg
    | whiskerLeft X f f' hf ih => exact HomEquiv.whiskerLeft _ _ _ ih
    | whiskerRight f f' X hf ih => exact HomEquiv.whiskerRight _ _ _ ih
    | tensor hf hg ihf ihg => exact HomEquiv.tensor ihf ihg
    | tensorHom_def f g => exact HomEquiv.tensorHom_def (f.project map) (g.project map)
    | comp_id f => exact HomEquiv.comp_id (f.project map)
    | id_comp f => exact HomEquiv.id_comp (f.project map)
    | assoc f g h => exact HomEquiv.assoc (f.project map) (g.project map) (h.project map)
    | id_tensorHom_id => exact HomEquiv.id_tensorHom_id
    | tensorHom_comp_tensorHom f₁ f₂ g₁ g₂ =>
        exact HomEquiv.tensorHom_comp_tensorHom (f₁.project map) (f₂.project map)
            (g₁.project map) (g₂.project map)
    | whiskerLeft_id X Y => exact HomEquiv.whiskerLeft_id (X.project map) (Y.project map)
    | id_whiskerRight X Y => exact HomEquiv.id_whiskerRight (X.project map) (Y.project map)
    | α_hom_inv => exact HomEquiv.α_hom_inv
    | α_inv_hom => exact HomEquiv.α_inv_hom
    | associator_naturality f₁ f₂ f₃ =>
        exact HomEquiv.associator_naturality (f₁.project map) (f₂.project map) (f₃.project map)
    | ρ_hom_inv => exact HomEquiv.ρ_hom_inv
    | ρ_inv_hom => exact HomEquiv.ρ_inv_hom
    | ρ_naturality f => exact HomEquiv.ρ_naturality (f.project map)
    | l_hom_inv => exact HomEquiv.l_hom_inv
    | l_inv_hom => exact HomEquiv.l_inv_hom
    | l_naturality f => exact HomEquiv.l_naturality (f.project map)
    | pentagon => exact HomEquiv.pentagon
    | triangle => exact HomEquiv.triangle
    | σ_inv_left => exact HomEquiv.σ_inv_left
    | σ_inv_right => exact HomEquiv.σ_inv_right
    | braiding_naturality_right f =>
        exact HomEquiv.braiding_naturality_right (f.project map)
    | braiding_naturality_left f Z =>
        exact HomEquiv.braiding_naturality_left (f.project map) (Z.project map)
    | hexagon_forward => exact HomEquiv.hexagon_forward
    | hexagon_reverse => exact HomEquiv.hexagon_reverse

/-- Setoid for braid morphisms. -/
def setoidHom {α : Type u} (X Y : Monoid α) : Setoid (X ⟶ᵇ Y) :=
    ⟨HomEquiv, ⟨HomEquiv.refl, HomEquiv.symm _ _, HomEquiv.trans⟩⟩

section BraidInstance -- so "open HomEquiv" doesn't pollute outside

open HomEquiv

instance (α : Type u) : Category.{u} (Monoid α) where
    Hom X Y := Quotient (BraidGroupoid.setoidHom X Y)
    id X := ⟦Hom.id X⟧
    comp := Quotient.map₂ Hom.comp (fun _ _ hf _ _ hg ↦ HomEquiv.comp hf hg)
    id_comp := by
        rintro X Y ⟨f⟩
        exact Quotient.sound (id_comp f)
    comp_id := by
        rintro X Y ⟨f⟩
        exact Quotient.sound (comp_id f)
    assoc := by
        rintro W X Y Z ⟨f⟩ ⟨g⟩ ⟨h⟩
        exact Quotient.sound (assoc f g h)

instance (α : Type u) : MonoidalCategory (Monoid α) where
    tensorObj X Y := Monoid.tensor X Y
    tensorHom := Quotient.map₂ Hom.tensor (fun _ _ hf _ _ hg ↦ HomEquiv.tensor hf hg)
    whiskerLeft X _ _ f :=
        Quot.map (fun f ↦ Hom.whiskerLeft X f) (fun f f' ↦ .whiskerLeft X f f') f
    whiskerRight f Y :=
        Quot.map (fun f ↦ Hom.whiskerRight f Y) (fun f f' ↦ .whiskerRight f f' Y) f
    tensorHom_def {W X Y Z} := by
        rintro ⟨f⟩ ⟨g⟩
        exact Quotient.sound (tensorHom_def _ _)
    id_tensorHom_id _ _ := Quot.sound id_tensorHom_id
    tensorHom_comp_tensorHom {X₁ Y₁ Z₁ X₂ Y₂ Z₂} := by
        rintro ⟨f₁⟩ ⟨f₂⟩ ⟨g₁⟩ ⟨g₂⟩
        exact Quotient.sound (tensorHom_comp_tensorHom _ _ _ _)
    whiskerLeft_id X Y := Quot.sound (HomEquiv.whiskerLeft_id X Y)
    id_whiskerRight X Y := Quot.sound (HomEquiv.id_whiskerRight X Y)
    tensorUnit := Monoid.unit
    associator X Y Z :=
        ⟨⟦Hom.α_hom X Y Z⟧, ⟦Hom.α_inv X Y Z⟧, Quotient.sound α_hom_inv,
            Quotient.sound α_inv_hom⟩
    associator_naturality {X₁ X₂ X₃ Y₁ Y₂ Y₃} := by
        rintro ⟨f₁⟩ ⟨f₂⟩ ⟨f₃⟩
        exact Quotient.sound (associator_naturality _ _ _)
    leftUnitor X :=
        ⟨⟦Hom.l_hom X⟧, ⟦Hom.l_inv X⟧, Quotient.sound l_hom_inv,
            Quotient.sound l_inv_hom⟩
    leftUnitor_naturality {X Y} := by
        rintro ⟨f⟩
        exact Quotient.sound (l_naturality _)
    rightUnitor X :=
        ⟨⟦Hom.ρ_hom X⟧, ⟦Hom.ρ_inv X⟧, Quotient.sound ρ_hom_inv,
            Quotient.sound ρ_inv_hom⟩
    rightUnitor_naturality {X Y} := by
        rintro ⟨f⟩
        exact Quotient.sound (ρ_naturality _)
    pentagon _ _ _ _ := Quotient.sound pentagon
    triangle _ _ := Quotient.sound triangle

instance (α : Type u) : BraidedCategory (Monoid α) where
    braiding X Y :=
        ⟨⟦Hom.σ X Y⟧, ⟦Hom.σ_inv X Y⟧,
            Quotient.sound σ_inv_left, Quotient.sound σ_inv_right⟩
    braiding_naturality_right := by
        rintro X Y Z ⟨f⟩
        exact Quotient.sound (HomEquiv.braiding_naturality_right f)
    braiding_naturality_left := by
        rintro X Y ⟨f⟩ Z
        exact Quotient.sound (HomEquiv.braiding_naturality_left f Z)
    hexagon_forward := by
        intro X Y Z
        exact Quotient.sound (HomEquiv.hexagon_forward (X := X) (Y := Y) (Z := Z))
    hexagon_reverse := by
        intro X Y Z
        exact Quotient.sound (HomEquiv.hexagon_reverse (X := X) (Y := Y) (Z := Z))

end BraidInstance

def projectMap {α β : Type u} (map : α → Option β) (X Y : Monoid α) :
        (X ⟶ Y) → (X.project map ⟶ Y.project map) :=
    Quotient.lift (fun f => ⟦f.project map⟧) (by
        intro f g h
        exact Quotient.sound (HomEquiv.project map h))

def projectFunctor {α β : Type u} (map : α → Option β) : Monoid α ⥤ Monoid β where
    obj X := X.project map
    map {X Y} f := projectMap map X Y f
    map_id X := rfl
    map_comp {X Y Z} := by
        rintro ⟨f⟩ ⟨g⟩
        rfl

@[simp]
instance projectFunctor_laxMonoidal {α β : Type u} (map : α → Option β) :
        (projectFunctor map).LaxMonoidal where
    ε := 𝟙 _
    μ _ _ := 𝟙 _
    μ_natural_left := by
        rintro X Y ⟨f⟩ X'
        cat_disch
    μ_natural_right := by
        rintro X Y X' ⟨f⟩
        cat_disch

instance projectFunctor_laxBraided {α β : Type u} (map : α → Option β) :
        (projectFunctor map).LaxBraided where

@[simp]
theorem mk_comp {α : Type u} {X Y Z : Monoid α} (f : Hom X Y) (g : Hom Y Z) :
        ⟦f.comp g⟧ = @CategoryStruct.comp (Monoid α) _ _ _ _ ⟦f⟧ ⟦g⟧ :=
  rfl

@[simp]
theorem mk_tensor {α : Type u} {X₁ Y₁ X₂ Y₂ : Monoid α} (f : Hom X₁ Y₁) (g : Hom X₂ Y₂) :
        ⟦f.tensor g⟧ = @MonoidalCategory.tensorHom (Monoid α) _ _ _ _ _ _ ⟦f⟧ ⟦g⟧ :=
  rfl

@[simp]
theorem mk_whiskerLeft {α : Type u} (X : Monoid α) {Y₁ Y₂ : Monoid α} (f : Hom Y₁ Y₂) :
        ⟦f.whiskerLeft X⟧ =
            MonoidalCategory.whiskerLeft (C := Monoid α) (X := X) (f := ⟦f⟧) :=
  rfl

@[simp]
theorem mk_whiskerRight {α : Type u} {X₁ X₂ : Monoid α} (f : Hom X₁ X₂) (Y : Monoid α) :
        ⟦f.whiskerRight Y⟧ =
            MonoidalCategory.whiskerRight (C := Monoid α) (f := ⟦f⟧) (Y := Y) :=
  rfl

@[simp]
theorem mk_id {α : Type u} {X : Monoid α} : ⟦Hom.id X⟧ = 𝟙 X :=
  rfl

@[simp]
theorem mk_α_hom {α : Type u} {X Y Z : Monoid α} : ⟦Hom.α_hom X Y Z⟧ = (α_ X Y Z).hom :=
  rfl

@[simp]
theorem mk_α_inv {α : Type u} {X Y Z : Monoid α} : ⟦Hom.α_inv X Y Z⟧ = (α_ X Y Z).inv :=
  rfl

@[simp]
theorem mk_ρ_hom {α : Type u} {X : Monoid α} : ⟦Hom.ρ_hom X⟧ = (ρ_ X).hom :=
  rfl

@[simp]
theorem mk_ρ_inv {α : Type u} {X : Monoid α} : ⟦Hom.ρ_inv X⟧ = (ρ_ X).inv :=
  rfl

@[simp]
theorem mk_l_hom {α : Type u} {X : Monoid α} : ⟦Hom.l_hom X⟧ = (λ_ X).hom :=
  rfl

@[simp]
theorem mk_l_inv {α : Type u} {X : Monoid α} : ⟦Hom.l_inv X⟧ = (λ_ X).inv :=
    rfl

@[simp]
theorem mk_σ {α : Type u} {X Y : Monoid α} :
        (⟦Hom.σ X Y⟧ : (X ⊗ Y) ⟶ (Y ⊗ X)) = (β_ X Y).hom :=
    rfl

@[simp]
theorem mk_σ_inv {α : Type u} {X Y : Monoid α} :
        (⟦Hom.σ_inv X Y⟧ : (Y ⊗ X) ⟶ (X ⊗ Y)) = (β_ X Y).inv :=
  rfl

/-- The abbreviation for `⟦f⟧`. -/
/- This is useful since the notation `⟦f⟧` often behaves like an element of the quotient set,
but not like a morphism. This is why we need weird `@CategoryStruct.comp (Monoid α) ...` in the
statement in `mk_comp` above. -/
abbrev homMk {α : Type u} {X Y : Monoid α} (f : Hom X Y) : X ⟶ Y := ⟦f⟧


@[simp]
theorem tensor_eq_tensor {α : Type u} {X Y : Monoid α} : X.tensor Y = X ⊗ Y :=
  rfl

@[simp]
theorem unit_eq_unit {α : Type u} : Monoid.unit (α := α) = 𝟙_ (Monoid α) :=
  rfl

theorem Hom.inductionOn {α : Type u}
        {motive : {X Y : Monoid α} → (X ⟶ Y) → Prop} {X Y : Monoid α} (t : X ⟶ Y)
        (id : (X : Monoid α) → motive (𝟙 X))
        (α_hom : (X Y Z : Monoid α) → motive (α_ X Y Z).hom)
        (α_inv : (X Y Z : Monoid α) → motive (α_ X Y Z).inv)
        (l_hom : (X : Monoid α) → motive (λ_ X).hom)
        (l_inv : (X : Monoid α) → motive (λ_ X).inv)
        (ρ_hom : (X : Monoid α) → motive (ρ_ X).hom)
        (ρ_inv : (X : Monoid α) → motive (ρ_ X).inv)
        (σ_hom : (X Y : Monoid α) → motive (homMk (Hom.σ X Y)))
        (σ_inv : (X Y : Monoid α) → motive (homMk (Hom.σ_inv X Y)))
        (comp : {X Y Z : Monoid α} → (f : X ⟶ Y) → (g : Y ⟶ Z) →
            motive f → motive g → motive (f ≫ g))
        (whiskerLeft : {Y Z : Monoid α} → (X : Monoid α) → (f : Y ⟶ Z) →
            motive f → motive (X ◁ f))
        (whiskerRight : {X Y : Monoid α} → (f : X ⟶ Y) → (Z : Monoid α) →
            motive f → motive (f ▷ Z)) :
        motive t := by
    apply Quotient.inductionOn
    intro f
    induction f with
    | id X => exact id X
    | α_hom X Y Z => exact α_hom X Y Z
    | α_inv X Y Z => exact α_inv X Y Z
    | l_hom X => exact l_hom X
    | l_inv X => exact l_inv X
    | ρ_hom X => exact ρ_hom X
    | ρ_inv X => exact ρ_inv X
    | σ X Y => exact σ_hom X Y
    | σ_inv X Y => exact σ_inv X Y
    | comp f g hf hg => exact comp _ _ (hf ⟦f⟧) (hg ⟦g⟧)
    | whiskerLeft X f hf => exact whiskerLeft X _ (hf ⟦f⟧)
    | whiskerRight f X hf => exact whiskerRight _ X (hf ⟦f⟧)
    | @tensor W X Y Z f g hf hg =>
            have : homMk f ⊗ₘ homMk g = homMk f ▷ X ≫ Y ◁ homMk g :=
                Quotient.sound (HomEquiv.tensorHom_def f g)
            change motive (homMk f ⊗ₘ homMk g)
            rw [this]
            exact comp _ _ (whiskerRight _ _ (hf ⟦f⟧)) (whiskerLeft _ _ (hg ⟦g⟧))

theorem isIso_quot {α : Type u} {X Y : Monoid α} (f : X ⟶ Y) : IsIso f := by
    refine Hom.inductionOn (α := α) (t := f)
        (id := fun X => by simpa using (inferInstance : IsIso (𝟙 X)))
        (α_hom := fun X Y Z => by
            simpa using (inferInstance : IsIso (α_ X Y Z).hom))
        (α_inv := fun X Y Z => by
            simpa using (inferInstance : IsIso (α_ X Y Z).inv))
        (l_hom := fun X => by
            simpa using (inferInstance : IsIso (λ_ X).hom))
        (l_inv := fun X => by
            simpa using (inferInstance : IsIso (λ_ X).inv))
        (ρ_hom := fun X => by
            simpa using (inferInstance : IsIso (ρ_ X).hom))
        (ρ_inv := fun X => by
            simpa using (inferInstance : IsIso (ρ_ X).inv))
        (σ_hom := fun X Y => by
            simpa using
              (inferInstance : IsIso (β_ X Y).hom))
        (σ_inv := fun X Y => by
            simpa using
              (inferInstance : IsIso (β_ X Y).inv))
        (comp := fun f g hf hg ↦ by
            simpa using (inferInstance : IsIso (f ≫ g)))
        (whiskerLeft := fun X f hf => by
            simpa using (inferInstance : IsIso (X ◁ f)))
        (whiskerRight := fun f Z hf ↦ by
            simpa using (inferInstance : IsIso (f ▷ Z)))

noncomputable instance (α : Type u) : Groupoid (Monoid α) :=
    Groupoid.ofIsIso (C := Monoid α) (fun f => isIso_quot (α := α) f)

class BraidedGroupoid (C : Type u) [Category C] [MonoidalCategory C] [BraidedCategory C] [Groupoid C]

instance (α : Type u) : BraidedGroupoid (Monoid α) where

#check Functor

end BraidGroupoid
