import Mathlib
import LeanCategory.Egger
import LeanCategory.StarMonoid

/- Given a quiver over a monoid, construct the free twisted involutive monoidal category
generated by that quiver -/

variable {V : Type u}

section
variable (V)

-- type synonym: strict twisted monoidal product
@[grind]
structure S where
  val : V

instance : Coe V (S V) where
  coe v := ⟨v⟩
end

@[ext]
lemma S.ext {x y : S V} : x.val = y.val → x = y := by
  grind

variable [StarMonoid V] [Quiver.{v} V]

inductive Hom : V → V → Type max u v
  | of : (X ⟶ Y) → Hom X Y -- from the quiver
  | id : (X : V) → Hom X X
  | comp {X Y Z} (f : Hom X Y) (g : Hom Y Z) : Hom X Z
  | tensor {W X Y Z} (f : Hom W Y) (g : Hom X Z) : Hom (W * X) (Y * Z)
  | star {X Y} (f : Hom X Y) : Hom X⋆ Y⋆
  | twist_hom (X : V) : Hom X X⋆
  | twist_inv (X : V) : Hom X⋆ X

open CategoryTheory

-- gives us notation
instance : StarMonoid (S V) where
  one := (1 : V)
  mul X Y := X.val * Y.val
  mul_assoc A B C := S.ext <| mul_assoc A.val B.val C.val
  one_mul A := S.ext <| one_mul A.val
  mul_one A := S.ext <| mul_one A.val
  star X := ↑X.val⋆
  star_involutive X := S.ext <| star_involutive X.val
  star_mul X Y := S.ext <| StarMonoid.star_mul X.val Y.val

-- gives us notation
instance (priority := 100) preHom : CategoryStruct (S V) where
  Hom X Y := Hom X.val Y.val
  id X := Hom.id X.val
  comp := Hom.comp

-- synonym for Hom.Tensor that acts on the CategoryStruct notation
def myTensor {W X Y Z : S V} (f : W ⟶ Y) (g : X ⟶ Z) : (W * X) ⟶ (Y * Z) := Hom.tensor f g
infixr:70 " ⊗ " => myTensor

def myStar {X Y : S V} (f : X ⟶ Y) : X⋆ ⟶ Y⋆ := Hom.star f
postfix:max "⋆" => myStar

def ς_hom (X : S V) := Hom.twist_hom X.val
def ς_inv (X : S V) := Hom.twist_inv X.val

-- synonyms to make the monoidal category instance happy (IDK why Mathlib does it this way)
@[simp, grind]
def Hom.whiskerLeft (X : S V) {Y₁ Y₂ : S V} (f : Y₁ ⟶ Y₂) : (X * Y₁) ⟶ (X * Y₂) :=
  (𝟙 X) ⊗ f

@[simp, grind]
def Hom.whiskerRight {X₁ X₂ : S V} (f : X₁ ⟶ X₂) (Y : S V) : (X₁ * Y) ⟶ (X₂ * Y) :=
  f ⊗ (𝟙 Y)

infixr:81 " ◁ " => Hom.whiskerLeft
infixl:81 " ▷ " => Hom.whiskerRight

@[grind]
inductive HomEquiv : ∀ {A B : S V}, (A ⟶ B) → (A ⟶ B) → Prop
  | refl (f : X ⟶ Y) : HomEquiv f f
  | assoc (f : W ⟶ X) (g : X ⟶ Y) (h : Y ⟶ Z) :
      HomEquiv ((f ≫ g) ≫ h) (f ≫ (g ≫ h))
  | comp_id (f : X ⟶ Y) : HomEquiv (f ≫ (𝟙 _)) f
  | id_comp (f : X ⟶ Y) : HomEquiv ((𝟙 _ ) ≫ f) f
  -- congruence
  | comp {f f' : X ⟶ Y} {g g' : Y ⟶ Z} :
      HomEquiv f f' → HomEquiv g g' → HomEquiv (f ≫ g) (f' ≫ g')
  | tensor {f f' : W ⟶ X} {g g' : Y ⟶ Z} :
      HomEquiv f f' → HomEquiv g g' → HomEquiv (f ⊗ g) (f' ⊗ g')
  | star {f f' : X ⟶ Y} :
      HomEquiv f f' → HomEquiv f⋆ f'⋆
  -- (bi)functoriality
  | id_tensor_id {X Y : S V} : HomEquiv ((𝟙 X) ⊗ (𝟙 Y)) (𝟙 _)
  | tensor_comp_tensor (f₁ : X₁ ⟶ Y₁) (f₂ : X₂ ⟶ Y₂)
      (g₁ : Y₁ ⟶ Z₁) (g₂ : Y₂ ⟶ Z₂) :
      HomEquiv ((f₁ ⊗ f₂) ≫ (g₁ ⊗ g₂)) ((f₁ ≫ g₁) ⊗ (f₂ ≫ g₂))
  | star_id {X : S V}: HomEquiv (𝟙 X)⋆ (𝟙 X⋆)
  | star_comp_star (f : X ⟶ Y) (g : Y ⟶ Z) :
      HomEquiv (f ≫ g)⋆ (f⋆ ≫ g⋆)
  -- replacing the natural isomorphisms
  | tensor_assoc (f : P ⟶ Q) (g : W ⟶ X) (h : Y ⟶ Z) :
      HomEquiv (((f ⊗ g) ⊗ h) ≫ (eqToHom (mul_assoc Q X Z)))
        ((eqToHom (mul_assoc P W Y)) ≫ (f ⊗ (g ⊗ h)))
  | id_tensor (f : X ⟶ Y) :
      HomEquiv (((𝟙 1) ⊗ f) ≫ (eqToHom (one_mul Y))) ((eqToHom (one_mul X)) ≫ f)
  | tensor_id (f : X ⟶ Y) :
      HomEquiv ((f ⊗ (𝟙 1)) ≫ (eqToHom (mul_one Y))) ((eqToHom (mul_one X)) ≫ f)
  | star_skew (f : W ⟶ X) (g : Y ⟶ Z) :
      HomEquiv ((f⋆ ⊗ g⋆) ≫ (eqToHom (StarMonoid.star_mul Z X).symm))
        ((eqToHom (StarMonoid.star_mul Y W).symm) ≫ (g ⊗ f)⋆)
  | star_inv (f : X ⟶ Y) :
      HomEquiv (f⋆⋆ ≫ (eqToHom (star_involutive Y))) ((eqToHom (star_involutive X)) ≫ f)
  -- special facts about the twist
  | twist_hom_inv :
      HomEquiv ((ς_hom X) ≫ (ς_inv X)) (𝟙 X)
  | twist_inv_hom :
      HomEquiv ((ς_inv X) ≫ (ς_hom X)) (𝟙 X⋆)
  | twist_naturality (f : X ⟶ Y) :
      HomEquiv (f⋆ ≫ (ς_inv Y)) ((ς_inv X) ≫ f)
  | tℓ (P Q R : S V) : HomEquiv
      ((((eqToHom (StarMonoid.star_mul Q⋆ P⋆).symm) ≫ (ς_inv (Q⋆ * P⋆))) ⊗ (𝟙 R⋆⋆)) ≫
        (eqToHom (mul_assoc Q⋆ P⋆ R⋆⋆)) ≫ ((𝟙 Q⋆) ⊗ ((eqToHom (StarMonoid.star_mul R⋆ P).symm) ≫
        (ς_inv (R⋆ * P)))) ≫ (eqToHom (mul_assoc Q⋆ R⋆ P).symm) ≫
        (((eqToHom (StarMonoid.star_mul R Q).symm) ≫ (ς_inv (R * Q))) ⊗ (𝟙 P)) ≫
        (eqToHom (mul_assoc R Q P)))
      ((((ς_inv P⋆) ⊗ (ς_inv Q⋆)) ⊗ (ς_inv R⋆)) ≫
        ((eqToHom (StarMonoid.star_mul Q P).symm) ⊗ (𝟙 R⋆)) ≫
        (eqToHom (StarMonoid.star_mul R (Q * P)).symm) ≫ (ς_inv (R * (Q * P))))
  -- symm/trans last for constructor tactic
  | symm (f g : X ⟶ Y) : HomEquiv f g → HomEquiv g f
  | trans {f g h : X ⟶ Y} : HomEquiv f g → HomEquiv g h → HomEquiv f h

attribute [refl] HomEquiv.refl
attribute [symm] HomEquiv.symm

instance {A B : S V} : HasEquiv (A ⟶ B) where
  Equiv := HomEquiv

-- helps grind slog through notation
@[grind =_]
lemma HomEquiv.equiv_def {X Y : S V} {f g : X ⟶ Y} : HomEquiv f g ↔ f ≈ g := by
  constructor
  all_goals intros h
  all_goals exact h

lemma eqToHom_comp {X Y Z : S V} {f : X ⟶ Y} {g : Y ⟶ Z} {p : X = Y} {q : Y = Z} :
    (f ≈ eqToHom p) → (g ≈ eqToHom q) → (f ≫ g) ≈ (eqToHom (p.trans q)) := by
  intros hf hg
  apply HomEquiv.trans
  · exact HomEquiv.comp hf hg
  · cases p
    cases q
    simp
    grind

lemma eqToHom_tensor {W X Y Z : S V} {f : W ⟶ X} {g : Y ⟶ Z} {p : W = X} {q : Y = Z} :
    (f ≈ eqToHom p) → (g ≈ eqToHom q) → (f ⊗ g) ≈ (eqToHom (by simp [p, q])) := by
  intros hf hg
  apply HomEquiv.trans
  · exact HomEquiv.tensor hf hg
  cases p
  cases q
  simp
  grind

lemma eqToHom_star {X Y : S V} {f : X ⟶ Y} {p : X = Y} :
    (f ≈ eqToHom p) → f⋆ ≈ (eqToHom (by simp [p])) := by
  intros hf
  apply HomEquiv.trans
  · exact HomEquiv.star hf
  cases p
  simp
  grind

-- Attempts to take one step of simplifying a bunch of eqToHom/id to one eqToHom
macro "reduce_eqToHom_step" : tactic =>
  `(tactic|
    first
      | apply eqToHom_comp
      | apply eqToHom_tensor
      | apply eqToHom_star
      | rfl
  )

-- shows any combination of eqToHom/id is HomEquiv to a single eqToHom
macro "reduce_eqToHom" : tactic =>
  `(tactic|
    repeat' reduce_eqToHom_step
  )

-- shows any combinations of eqToHom/id HomEquiv to each other
macro "eqToHom_eq_eqToHom" : tactic =>
  `(tactic|
    apply HomEquiv.trans (by reduce_eqToHom) (by symm; reduce_eqToHom)
  )

lemma HomEquiv.whiskerLeft (X : S V) {Y Z} {f f' : Y ⟶ Z} (h : f ≈ f') :
    (X ◁ f) ≈ (X ◁ f') := by grind

lemma HomEquiv.whiskerRight {X Y} {f f' : X ⟶ Y} (Z : S V) (h : f ≈ f') :
    (f ▷ Z) ≈ (f' ▷ Z) := by grind

lemma HomEquiv.tensorHom_def {X₁ Y₁ X₂ Y₂ : S V} (f : X₁ ⟶ Y₁) (g : X₂ ⟶ Y₂) :
    (f ⊗ g) ≈ (f ▷ X₂ ≫ Y₁ ◁ g) := by grind [tensor_comp_tensor]

lemma HomEquiv.whiskerLeft_id (X Y : S V) : (X ◁ (𝟙 Y)) ≈ (𝟙 (X * Y)) := by
  grind

lemma HomEquiv.id_whiskerRight (X Y : S V) : ((𝟙 X) ▷ Y) ≈ (𝟙 (X * Y)) := by
  grind

instance setoidHom (X Y : S V) : Setoid (X ⟶ Y) :=
⟨HomEquiv, ⟨HomEquiv.refl, HomEquiv.symm _ _, HomEquiv.trans⟩⟩

open HomEquiv

instance : Category (S V) where
  Hom X Y := Quotient (setoidHom X Y)
  id X := ⟦𝟙 X⟧
  comp f g := Quotient.map₂ (· ≫ ·) (fun _ _ hf _ _ hg ↦ HomEquiv.comp hf hg) f g
  id_comp {X Y} := by
    rintro ⟨f⟩
    apply Quotient.sound
    grind
  comp_id {X Y} := by
    rintro ⟨f⟩
    apply Quotient.sound
    grind
  assoc {W X Y Z} := by
    rintro ⟨f⟩ ⟨g⟩ ⟨h⟩
    apply Quotient.sound
    grind

-- not eqToIso! Can't see much hope of generalizing this one
def eqToIso' {X Y : S V} (h : X = Y) : X ≅ Y := {
  hom := ⟦@eqToHom _ preHom _ _ h⟧
  inv := ⟦@eqToHom _ preHom _ _ h.symm⟧
  hom_inv_id := by
    apply Quotient.sound
    exact eqToHom_comp (by rfl) (by rfl)
  inv_hom_id := by
    apply Quotient.sound
    exact eqToHom_comp (by rfl) (by rfl)
}

-- TODO use ofTensorHom to dodge the nasty whiskers
instance : MonoidalCategory (S V) where
  tensorObj X Y := X * Y
  tensorHom f g := Quotient.map₂ (· ⊗ ·) (fun _ _ hf _ _ hg ↦ HomEquiv.tensor hf hg) f g
  tensorUnit := 1
  associator X Y Z := eqToIso' (mul_assoc X Y Z)
  leftUnitor X := eqToIso' (one_mul X)
  rightUnitor X := eqToIso' (mul_one X)
  whiskerLeft X {Y₁ Y₂} f := Quotient.map (X ◁ ·) (fun _ _ hf ↦ HomEquiv.whiskerLeft X hf) f
  whiskerRight {X₁ X₂} f Y := Quotient.map (· ▷ Y) (fun _ _ hf ↦ HomEquiv.whiskerRight Y hf) f
  tensorHom_def {X₁ Y₁ X₂ Y₂} := by
    rintro ⟨f⟩ ⟨g⟩
    apply Quotient.sound
    apply HomEquiv.tensorHom_def
  id_tensorHom_id _ _ := Quotient.sound id_tensor_id
  tensorHom_comp_tensorHom {X₁ Y₁ Z₁ X₂ Y₂ Z₂} := by -- TODO can this be sound?
    rintro ⟨f₁⟩ ⟨f₂⟩ ⟨g₁⟩ ⟨g₂⟩
    apply Quotient.sound
    grind
  whiskerLeft_id X Y := Quotient.sound (HomEquiv.whiskerLeft_id X Y)
  id_whiskerRight X Y := Quotient.sound (HomEquiv.id_whiskerRight X Y)
  associator_naturality {X₁ X₂ X₃ Y₁ Y₂ Y₃} := by
    rintro ⟨f₁⟩ ⟨f₂⟩ ⟨f₃⟩
    apply Quotient.sound
    grind
  leftUnitor_naturality {X Y} := by
    rintro ⟨f⟩
    apply Quotient.sound
    grind
  rightUnitor_naturality {X Y} := by
    rintro ⟨f⟩
    apply Quotient.sound
    grind
  pentagon W X Y Z := by
    apply Quotient.sound
    eqToHom_eq_eqToHom
  triangle X Y := by
    apply Quotient.sound
    eqToHom_eq_eqToHom

instance : InvolutiveCategory (S V) where
  starObj X := X⋆
  starHom f := Quotient.map (·⋆) (fun _ _ hf ↦ HomEquiv.star hf) f
  skewator X Y := eqToIso' (StarMonoid.star_mul Y X).symm
  involutor X := eqToIso' (star_involutive X)
  starHom_id _ := Quotient.sound star_id
  starHom_comp_starHom {X Y Z} := by
    rintro ⟨f⟩ ⟨g⟩
    apply Quotient.sound
    grind
  skewator_naturality {W X Y Z} := by
    rintro ⟨f⟩ ⟨g⟩
    apply Quotient.sound
    apply star_skew
  involutor_naturality {X Y} := by
    rintro ⟨f⟩
    apply Quotient.sound
    grind
  f3 X Y Z := by
    apply Quotient.sound
    eqToHom_eq_eqToHom
  n2 X Y := by
    apply Quotient.sound
    eqToHom_eq_eqToHom
  a X := by
    apply Quotient.sound
    eqToHom_eq_eqToHom

instance : TwistedCategory (S V) where
  twist X := {
    hom := ⟦ς_inv X⟧
    inv := ⟦ς_hom X⟧
    hom_inv_id := by
      apply Quotient.sound
      constructor
    inv_hom_id := by
      apply Quotient.sound
      constructor
  }
  twist_naturality {X Y} := by
    rintro ⟨f⟩
    apply Quotient.sound
    constructor
  tℓ X Y Z := by
    apply Quotient.sound
    constructor
