import Mathlib
import LeanCategory.Egger

/- Given a quiver over a monoid, construct the free monoidal category
generated by that quiver -/

postfix:max "⋆" => Star.star

class StarMonoid (R : Type u) extends Monoid R, InvolutiveStar R where
  /-- `star` skew-distributes over multiplication. -/
  star_mul : ∀ r s : R, (r * s)⋆ = s⋆ * r⋆ := by aesop

variable {V : Type u} [StarMonoid V] [Quiver.{v} V]

-- type synonym: strict twisted monoidal product
notation "S " => id

inductive Hom : V → V → Type max u v
  | of : (X ⟶ Y) → Hom X Y -- from the quiver
  | id : (X : V) → Hom X X
  | comp {X Y Z} (f : Hom X Y) (g : Hom Y Z) : Hom X Z
  | tensor {W X Y Z} (f : Hom W Y) (g : Hom X Z) : Hom (W * X) (Y * Z)
  | star {X Y} (f : Hom X Y) : Hom X⋆ Y⋆
  | twist_hom (X : S V) : Hom X X⋆
  | twist_inv (X : S V) : Hom X⋆ X

open CategoryTheory

#check StarMul
-- gives us notation
instance hism : StarMonoid (S V) where
  one := (1 : V)
  mul (X Y : V) := (X * Y : V)
  mul_assoc (A B C : V) := mul_assoc A B C
  one_mul (A : V) := one_mul A
  mul_one (A : V) := mul_one A
  star (X : V) := (X⋆ : V)
  star_involutive (X : V) := star_involutive X
  star_mul (X Y : V) := StarMonoid.star_mul X Y

-- gives us notation
instance histruct : CategoryStruct (S V) where
  Hom (X Y : V) := Hom X Y
  id (X : V) := Hom.id X
  comp := Hom.comp

-- synonym for Hom.Tensor that acts on the CategoryStruct notation
def myTensor {W X Y Z : S V} (f : W ⟶ Y) (g : X ⟶ Z) : (W * X) ⟶ (Y * Z) := Hom.tensor f g
infixr:70 " ⊗ " => myTensor

def myStar {X Y : S V} (f : X ⟶ Y) : X⋆ ⟶ Y⋆ := Hom.star f
postfix:max "⋆" => myStar

notation "ς_hom" => Hom.twist_hom
notation "ς_inv" => Hom.twist_inv

-- synonyms to make the monoidal category instance happy (IDK why Mathlib does it this way)
@[simp, grind]
def Hom.whiskerLeft (X : S V) {Y₁ Y₂ : S V} (f : Y₁ ⟶ Y₂) : (X * Y₁) ⟶ (X * Y₂) :=
  (𝟙 X) ⊗ f

@[simp, grind]
def Hom.whiskerRight {X₁ X₂ : S V} (f : X₁ ⟶ X₂) (Y : S V) : (X₁ * Y) ⟶ (X₂ * Y) :=
  f ⊗ (𝟙 Y)

infixr:81 " ◁ " => Hom.whiskerLeft
infixl:81 " ▷ " => Hom.whiskerRight

@[grind]
inductive HomEquiv : ∀ {A B : S V}, (A ⟶ B) → (A ⟶ B) → Prop
  | refl (f : X ⟶ Y) : HomEquiv f f
  | comp {f f' : X ⟶ Y} {g g' : Y ⟶ Z} :
      HomEquiv f f' → HomEquiv g g' → HomEquiv (f ≫ g) (f' ≫ g')
  | tensor {f f' : W ⟶ X} {g g' : Y ⟶ Z} :
      HomEquiv f f' → HomEquiv g g' → HomEquiv (f ⊗ g) (f' ⊗ g')
  | star {f f' : X ⟶ Y} :
      HomEquiv f f' → HomEquiv f⋆ g⋆
  | comp_id (f : X ⟶ Y) : HomEquiv (f ≫ (𝟙 _)) f
  | id_comp (f : X ⟶ Y) : HomEquiv ((𝟙 _ ) ≫ f) f
  | assoc (f : W ⟶ X) (g : X ⟶ Y) (h : Y ⟶ Z) :
      HomEquiv ((f ≫ g) ≫ h) (f ≫ (g ≫ h))
  | id_tensor_id {X Y : S V} : HomEquiv ((𝟙 X) ⊗ (𝟙 Y)) (𝟙 _)
  | tensor_comp_tensor (f₁ : X₁ ⟶ Y₁) (f₂ : X₂ ⟶ Y₂)
      (g₁ : Y₁ ⟶ Z₁) (g₂ : Y₂ ⟶ Z₂) :
      HomEquiv ((f₁ ⊗ f₂) ≫ (g₁ ⊗ g₂)) ((f₁ ≫ g₁) ⊗ (f₂ ≫ g₂))
  | star_id {X : S V}: HomEquiv (𝟙 X)⋆ (𝟙 X⋆)
  | star_comp_star (f : X ⟶ Y) (g : Y ⟶ Z) :
      HomEquiv (f ≫ g)⋆ (f⋆ ≫ g⋆)
  -- replacing the associator and unitors
  | tensor_assoc (f : P ⟶ Q) (g : W ⟶ X) (h : Y ⟶ Z) :
      HomEquiv (((f ⊗ g) ⊗ h) ≫ (eqToHom (mul_assoc Q X Z))) ((eqToHom (mul_assoc P W Y)) ≫ (f ⊗ (g ⊗ h)))
  | id_tensor (f : X ⟶ Y) : HomEquiv (((𝟙 1) ⊗ f) ≫ (eqToHom (one_mul Y))) ((eqToHom (one_mul X)) ≫ f)
  -- | id_tensor (f : X ⟶ Y) : HomEquiv ((𝟙 1) ⊗ f) f
  | tensor_id (f : X ⟶ Y) : HomEquiv ((f ⊗ (𝟙 1)) ≫ (eqToHom (mul_one Y))) ((eqToHom (mul_one X)) ≫ f)
  -- TODO something about ⋆ naturality
  | star_skew (f : W ⟶ X) (g : Y ⟶ Z) :
      HomEquiv ((f⋆ ⊗ g⋆) ≫ (eqToHom (StarMonoid.star_mul Z X).symm)) ((eqToHom (StarMonoid.star_mul Y W).symm) ≫ (g ⊗ f)⋆)
  | star_inv (f : X ⟶ Y) :
      HomEquiv (f⋆⋆ ≫ (eqToHom (star_involutive Y))) ((eqToHom (star_involutive X)) ≫ f)
  | twist_hom_inv :
      HomEquiv ((ς_hom X) ≫ (ς_inv X)) (𝟙 X)
  | twist_inv_hom :
      HomEquiv ((ς_inv X) ≫ (ς_hom X)) (𝟙 X⋆)
  | twist_naturality (f : X ⟶ Y) :
      HomEquiv (f⋆ ≫ (ς_inv Y)) ((ς_inv X) ≫ f)
  | symm (f g : X ⟶ Y) : HomEquiv f g → HomEquiv g f
  | trans {f g h : X ⟶ Y} : HomEquiv f g → HomEquiv g h → HomEquiv f h

attribute [grind] HomEquiv.refl
attribute [grind] HomEquiv.comp
attribute [grind] HomEquiv.tensor
attribute [grind] HomEquiv.star
attribute [grind] HomEquiv.comp_id
attribute [grind] HomEquiv.id_comp
attribute [grind] HomEquiv.assoc
attribute [grind] HomEquiv.id_tensor_id
attribute [grind] HomEquiv.tensor_comp_tensor
attribute [grind] HomEquiv.star_id
attribute [grind] HomEquiv.star_comp_star
attribute [grind] HomEquiv.tensor_assoc
attribute [grind] HomEquiv.id_tensor
attribute [grind] HomEquiv.tensor_id
attribute [grind] HomEquiv.star_skew
attribute [grind] HomEquiv.star_inv
attribute [grind] HomEquiv.twist_hom_inv
attribute [grind] HomEquiv.twist_inv_hom
attribute [grind] HomEquiv.twist_naturality
attribute [grind] HomEquiv.symm
attribute [grind] HomEquiv.trans

attribute [refl] HomEquiv.refl
attribute [symm] HomEquiv.symm
attribute [trans] HomEquiv.trans

instance {A B : S V} : HasEquiv (A ⟶ B) where
  Equiv := HomEquiv
instance {A B : S V} : Trans (HomEquiv (A := A) (B := B)) (HomEquiv (A := A) (B := B)) (HomEquiv (A := A) (B := B)) where
  trans := HomEquiv.trans

@[grind =_]
lemma HomEquiv.equiv_def {X Y : S V} {f g : X ⟶ Y} : HomEquiv f g ↔ f ≈ g := by
  constructor
  all_goals intros h
  all_goals exact h

@[simp, grind .]
lemma eqToHom_comp {X Y Z : S V} {p : X = Y} {q : Y = Z} : (eqToHom p ≫ eqToHom q) ≈ (eqToHom (p.trans q)) := by
  cases p
  cases q
  simp
  grind

@[simp, grind .]
lemma eqToHom_tensor {W X Y Z : S V} {p : W = X} {q : Y = Z} : (eqToHom p ⊗ eqToHom q) ≈ (eqToHom (by simp [p, q])) := by
  cases p
  cases q
  simp
  grind

@[simp]
lemma HomEquiv.whiskerLeft (X : S V) {Y Z} {f f' : Y ⟶ Z} (h : f ≈ f') :
    (X ◁ f) ≈ (X ◁ f') := by grind

@[simp]
lemma HomEquiv.whiskerRight {X Y} {f f' : X ⟶ Y} (Z : S V) (h : HomEquiv f f') :
    (f ▷ Z) ≈ (f' ▷ Z) := by grind

@[simp, grind .]
lemma HomEquiv.tensorHom_def {X₁ Y₁ X₂ Y₂ : S V} (f : X₁ ⟶ Y₁) (g : X₂ ⟶ Y₂) :
    (f ⊗ g) ≈ (f ▷ X₂ ≫ Y₁ ◁ g) := by grind [tensor_comp_tensor]

@[simp, grind]
lemma HomEquiv.whiskerLeft_id (X Y : S V) : (X ◁ (𝟙 Y)) ≈ (𝟙 (X * Y)) := by
  grind

@[simp, grind]
lemma HomEquiv.id_whiskerRight (X Y : S V) : ((𝟙 X) ▷ Y) ≈ (𝟙 (X * Y)) := by
  grind

instance setoidHom (X Y : S V) : Setoid (X ⟶ Y) :=
⟨HomEquiv, ⟨HomEquiv.refl, HomEquiv.symm _ _, HomEquiv.trans⟩⟩

def myHom (X Y : S V) := Quotient (setoidHom X Y)

@[grind =_]
lemma myHom_eq {X Y : S V} (f g : X ⟶ Y) : HomEquiv f g ↔ f ≈ g := by
  constructor
  all_goals intros h
  all_goals exact h

open HomEquiv

@[simp]
instance hicat : Category (S V) where
  Hom X Y := myHom X Y
  id X := ⟦𝟙 X⟧
  comp f g := Quotient.map₂ (· ≫ ·) (fun _ _ hf _ _ hg ↦ HomEquiv.comp hf hg) f g
  id_comp {X Y} := by
    rintro ⟨f⟩
    apply Quotient.sound
    grind
  comp_id {X Y} := by
    rintro ⟨f⟩
    apply Quotient.sound
    grind
  assoc {W X Y Z} := by
    rintro ⟨f⟩ ⟨g⟩ ⟨h⟩
    apply Quotient.sound
    grind

-- TODO a way to lift a star monoid equality to a Hom isomorphism for these natural transformations

def liftEquiv {X Y : S V} (h : X = Y) : X ≅ Y := {
  hom := ⟦eqToHom h⟧
  inv := ⟦eqToHom h.symm⟧
  hom_inv_id := by
    apply Quotient.sound
    apply eqToHom_comp
  inv_hom_id := by
    apply Quotient.sound
    apply eqToHom_comp
}

instance himon : MonoidalCategory (S V) where
  tensorObj X Y := X * Y
  tensorHom f g := Quotient.map₂ (· ⊗ ·) (fun _ _ hf _ _ hg ↦ HomEquiv.tensor hf hg) f g
  tensorUnit := 1
  associator X Y Z := liftEquiv (mul_assoc X Y Z)
  leftUnitor X := liftEquiv (one_mul X)
  rightUnitor X := liftEquiv (mul_one X)
  whiskerLeft X {Y₁ Y₂} f := Quotient.map (X ◁ ·) (fun _ _ hf ↦ HomEquiv.whiskerLeft X hf) f
  whiskerRight {X₁ X₂} f Y := Quotient.map (· ▷ Y) (fun _ _ hf ↦ HomEquiv.whiskerRight Y hf) f
  tensorHom_def {X₁ Y₁ X₂ Y₂} := by
    rintro ⟨f⟩ ⟨g⟩
    apply Quotient.sound
    grind
  id_tensorHom_id _ _ := Quotient.sound id_tensor_id
  tensorHom_comp_tensorHom {X₁ Y₁ Z₁ X₂ Y₂ Z₂} := by -- TODO can this be sound?
    rintro ⟨f₁⟩ ⟨f₂⟩ ⟨g₁⟩ ⟨g₂⟩
    apply Quotient.sound
    grind
  whiskerLeft_id X Y := Quotient.sound (HomEquiv.whiskerLeft_id X Y)
  id_whiskerRight X Y := Quotient.sound (HomEquiv.id_whiskerRight X Y)
  associator_naturality {X₁ X₂ X₃ Y₁ Y₂ Y₃} := by
    rintro ⟨f₁⟩ ⟨f₂⟩ ⟨f₃⟩
    apply Quotient.sound
    grind
  leftUnitor_naturality {X Y} := by
    rintro ⟨f⟩
    apply Quotient.sound
    grind
  rightUnitor_naturality {X Y} := by
    rintro ⟨f⟩
    apply Quotient.sound
    grind
  pentagon W X Y Z := by
    apply Quotient.sound
    simp
    trans
    · apply HomEquiv.comp
      · apply eqToHom_tensor
        rfl
      · apply HomEquiv.trans
        · apply HomEquiv.comp
          · rfl
          · apply eqToHom_tensor
            rfl
        · apply eqToHom_comp
    · grind [eqToHom_tensor, eqToHom_comp]
  triangle X Y := by
    simp
    apply Quotient.sound
    trans
    · trans
      · apply HomEquiv.comp
        · rfl
        · apply eqToHom_tensor
          rfl
      · apply eqToHom_comp
    · symm
      apply eqToHom_tensor
      rfl

instance hiinv : InvolutiveCategory (S V) where
  starObj X := X⋆
  starHom f := Quotient.map (·⋆) (fun _ _ hf ↦ HomEquiv.star hf) f
  skewator X Y := liftEquiv (StarMonoid.star_mul Y X).symm
  involutor X := liftEquiv (star_involutive X)
  starHom_id _ := Quotient.sound star_id
  starHom_comp_starHom {X Y Z} := by
    rintro ⟨f⟩ ⟨g⟩
    apply Quotient.sound
    grind
  skewator_naturality {W X Y Z} := by
    rintro ⟨f⟩ ⟨g⟩
    apply Quotient.sound
    apply star_skew
  involutor_naturality {X Y} := by
    rintro ⟨f⟩
    apply Quotient.sound
    grind
  f3 := sorry
  n2 := sorry
  a := sorry

instance hitwist : TwistedCategory (S V) where
  twist (X : V) := {
    hom := ⟦ς_inv X⟧
    inv := ⟦ς_hom X⟧
    hom_inv_id := by
      apply Quotient.sound
      constructor
    inv_hom_id := by
      apply Quotient.sound
      constructor
  }
  twist_naturality {X Y} := by
    rintro ⟨f⟩
    apply Quotient.sound
    constructor
  tℓ := sorry
