import Mathlib

/- Given a quiver over a monoid, construct the free monoidal category
generated by that quiver -/

variable {V : Type u} [Monoid V] [Quiver.{v} V]

postfix:max "⋆" => Star.star

class StarMonoid (R : Type u) [Monoid R] extends InvolutiveStar R where
  /-- `star` skew-distributes over multiplication. -/
  star_mul : ∀ r s : R, (r * s)⋆ = s⋆ * r⋆

inductive Hom : V → V → Type max u v
  | of : (X ⟶ Y) → Hom X Y -- from the quiver
  | id : (X : V) → Hom X X
  | comp {X Y Z} (f : Hom X Y) (g : Hom Y Z) : Hom X Z
  | tensor {W X Y Z} (f : Hom W Y) (g : Hom X Z) : Hom (W * X) (Y * Z)

open CategoryTheory

-- def StrictMonoidalProduct (X : Type u) := X

notation "S " => id

-- gives us notation
instance : Monoid (S V) where
  one := (1 : V)
  mul (X Y : V) := (X * Y : V)
  mul_assoc (A B C : V) := mul_assoc A B C
  one_mul (A : V) := one_mul A
  mul_one (A : V) := mul_one A

-- gives us notation
instance : CategoryStruct (S V) where
  Hom (X Y : V) := Hom X Y
  id (X : V) := Hom.id X
  comp := Hom.comp

-- synonym for Hom.Tensor that acts on the CategoryStruct notation
def myTensor {W X Y Z : S V} (f : W ⟶ Y) (g : X ⟶ Z) : (W * X) ⟶ (Y * Z) := Hom.tensor f g
infixr:70 " ⊗ " => myTensor

-- synonyms to make the monoidal category instance happy (IDK why Mathlib does it this way)
@[simp, grind]
def Hom.whiskerLeft (X : S V) {Y₁ Y₂ : S V} (f : Y₁ ⟶ Y₂) : (X * Y₁) ⟶ (X * Y₂) :=
  (𝟙 X) ⊗ f

@[simp, grind]
def Hom.whiskerRight {X₁ X₂ : S V} (f : X₁ ⟶ X₂) (Y : S V) : (X₁ * Y) ⟶ (X₂ * Y) :=
  f ⊗ (𝟙 Y)

infixr:81 " ◁ " => Hom.whiskerLeft
infixl:81 " ▷ " => Hom.whiskerRight

@[grind]
inductive HomEquiv : ∀ {A B : S V}, (A ⟶ B) → (A ⟶ B) → Prop
  | refl (f : X ⟶ Y) : HomEquiv f f
  | comp {f f' : X ⟶ Y} {g g' : Y ⟶ Z} :
      HomEquiv f f' → HomEquiv g g' → HomEquiv (f ≫ g) (f' ≫ g')
  | tensor {f f' : W ⟶ X} {g g' : Y ⟶ Z} :
      HomEquiv f f' → HomEquiv g g' → HomEquiv (f ⊗ g) (f' ⊗ g')
  | comp_id (f : X ⟶ Y) : HomEquiv (f ≫ (𝟙 _)) f
  | id_comp (f : X ⟶ Y) : HomEquiv ((𝟙 _ ) ≫ f) f
  | assoc (f : W ⟶ X) (g : X ⟶ Y) (h : Y ⟶ Z) :
      HomEquiv ((f ≫ g) ≫ h) (f ≫ (g ≫ h))
  | id_tensor_id {X Y : S V} : HomEquiv ((𝟙 X) ⊗ (𝟙 Y)) (𝟙 _)
  | tensor_comp_tensor (f₁ : X₁ ⟶ Y₁) (f₂ : X₂ ⟶ Y₂)
      (g₁ : Y₁ ⟶ Z₁) (g₂ : Y₂ ⟶ Z₂) :
    HomEquiv ((f₁ ⊗ f₂) ≫ (g₁ ⊗ g₂)) ((f₁ ≫ g₁) ⊗ (f₂ ≫ g₂))
  -- replacing the associator and unitors
  | tensor_assoc (f : P ⟶ Q) (g : W ⟶ X) (h : Y ⟶ Z) :
      HomEquiv (((f ⊗ g) ⊗ h) ≫ (eqToHom (mul_assoc Q X Z))) ((eqToHom (mul_assoc P W Y)) ≫ (f ⊗ (g ⊗ h)))
  | id_tensor (f : X ⟶ Y) : HomEquiv (((𝟙 1) ⊗ f) ≫ (eqToHom (one_mul Y))) ((eqToHom (one_mul X)) ≫ f)
  -- | id_tensor (f : X ⟶ Y) : HomEquiv ((𝟙 1) ⊗ f) f
  | tensor_id (f : X ⟶ Y) : HomEquiv ((f ⊗ (𝟙 1)) ≫ (eqToHom (mul_one Y))) ((eqToHom (mul_one X)) ≫ f)
  | symm (f g : X ⟶ Y) : HomEquiv f g → HomEquiv g f
  | trans {f g h : X ⟶ Y} : HomEquiv f g → HomEquiv g h → HomEquiv f h

attribute [grind] HomEquiv.refl
attribute [grind] HomEquiv.comp
attribute [grind] HomEquiv.tensor
attribute [grind] HomEquiv.comp_id
attribute [grind] HomEquiv.id_comp
attribute [grind] HomEquiv.assoc
attribute [grind] HomEquiv.id_tensor_id
attribute [grind] HomEquiv.tensor_comp_tensor
attribute [grind] HomEquiv.tensor_assoc
attribute [grind] HomEquiv.id_tensor
attribute [grind] HomEquiv.tensor_id
attribute [grind] HomEquiv.symm
attribute [grind] HomEquiv.trans

attribute [refl] HomEquiv.refl
attribute [symm] HomEquiv.symm
attribute [trans] HomEquiv.trans
-- instance {A B : S V} : _root_.Equivalence (HomEquiv (A := A) (B := B)) where
--   refl := HomEquiv.refl
--   symm := HomEquiv.symm _ _
--   trans := HomEquiv.trans
-- #check HasEquiv
instance {A B : S V} : HasEquiv (A ⟶ B) where
  Equiv := HomEquiv
instance {A B : S V} : Trans (HomEquiv (A := A) (B := B)) (HomEquiv (A := A) (B := B)) (HomEquiv (A := A) (B := B)) where
  trans := HomEquiv.trans

attribute [aesop safe] HomEquiv.refl
attribute [aesop safe] HomEquiv.comp
attribute [aesop safe] HomEquiv.tensor
attribute [aesop safe] HomEquiv.comp_id
attribute [aesop safe] HomEquiv.id_comp
attribute [aesop safe] HomEquiv.assoc -- TODO norm or not to norm?
attribute [aesop safe] HomEquiv.id_tensor_id
attribute [aesop safe] HomEquiv.tensor_comp_tensor
attribute [aesop safe] HomEquiv.tensor_assoc
attribute [aesop safe] HomEquiv.id_tensor
attribute [aesop safe] HomEquiv.tensor_id
-- just missing symm and trans
-- attribute [aesop unsafe 20%] HomEquiv.symm
-- attribute [aesop unsafe 10%] HomEquiv.trans

set_option trace.aesop true
-- set_option trace.aesop.tree true

@[grind =_]
lemma HomEquiv.equiv_def {X Y : S V} {f g : X ⟶ Y} : HomEquiv f g ↔ f ≈ g := by
  constructor
  all_goals intros h
  all_goals exact h

@[simp, grind .]
lemma eqToHom_comp {X Y Z : S V} {p : X = Y} {q : Y = Z} : (eqToHom p ≫ eqToHom q) ≈ (eqToHom (p.trans q)) := by
  cases p
  cases q
  simp
  grind
  -- apply HomEquiv.comp_id
  -- hom_equiv

@[simp, grind .]
lemma eqToHom_tensor {W X Y Z : S V} {p : W = X} {q : Y = Z} : (eqToHom p ⊗ eqToHom q) ≈ (eqToHom (by simp [p, q])) := by
  cases p
  cases q
  simp
  grind
  -- exact HomEquiv.id_tensor_id

-- macro "hom_close" : tactic =>
--   `(tactic|
--       (trace_state ; (first
--         -- closing goals
--         | assumption
--         | apply HomEquiv.comp_id
--         | apply HomEquiv.id_comp
--         | apply HomEquiv.assoc
--         | apply HomEquiv.id_tensor_id
--         | apply HomEquiv.tensor_comp_tensor
--         | apply HomEquiv.tensor_assoc
--         | apply HomEquiv.id_tensor
--         | apply HomEquiv.tensor_id
--         | apply hi'
--         | apply hi''
--         -- | apply HomEquiv.comp (by rfl)
--         -- | apply HomEquiv.comp ?_ (by rfl)
--         -- | apply HomEquiv.tensor (by rfl)
--         -- | apply HomEquiv.tensor ?_ (by rfl)
--         | fail "no steps to take!"
--       )
--       )
--   )

-- macro "hom_close_symm" : tactic =>
--   `(tactic|
--       first
--         | hom_close
--         | symm; hom_close
--   )

-- macro "hom_cong" : tactic =>
--   `(tactic|
--       (repeat1' (first
--         | hom_close
--         | apply HomEquiv.comp (by rfl) ?_
--         | apply HomEquiv.comp ?_ (by rfl)
--         | apply HomEquiv.tensor (by rfl) ?_
--         | apply HomEquiv.tensor ?_ (by rfl)
--         | fail "no steps to take!"
--         )
--       )
--   )

-- macro "hom_equiv" : tactic =>
--   `(tactic|
--     (repeat1'
--       trace_state ; (first
--         | simp
--         -- | trace_state
--         -- closing goals
--         | hom_close_symm
--         | rfl

--         -- unary
--         -- | apply hi'
--         -- | apply hi''

--         -- congruences (recursive)
--         | apply HomEquiv.comp
--         | apply HomEquiv.tensor

--         -- maybe apply a lemma?
--         -- meta rules (recursive)
--         | apply HomEquiv.trans (by hom_close)
--         | symm; apply HomEquiv.trans (by hom_close)
--         -- | apply HomEquiv.trans (by hom_cong)
--         -- | symm; apply HomEquiv.trans (by hom_cong)
--         | apply HomEquiv.trans (HomEquiv.comp (by rfl) (by hom_close))
--         | apply HomEquiv.trans (HomEquiv.tensor (by rfl) (by hom_close))
--         | apply HomEquiv.trans (HomEquiv.comp (by hom_close) (by rfl))
--         | apply HomEquiv.trans (HomEquiv.tensor (by hom_close) (by rfl))
--         | symm; apply HomEquiv.trans (HomEquiv.comp (by rfl) (by hom_close))
--         | symm; apply HomEquiv.trans (HomEquiv.tensor (by rfl) (by hom_close))
--         | symm; apply HomEquiv.trans (HomEquiv.comp (by hom_close) (by rfl))
--         | symm; apply HomEquiv.trans (HomEquiv.tensor (by hom_close) (by rfl))
--         | apply HomEquiv.trans (HomEquiv.comp (by rfl) (HomEquiv.comp (by hom_close) (by rfl)))
--         | apply HomEquiv.trans (HomEquiv.comp (by rfl) (HomEquiv.comp (by rfl) (by hom_close)))
--         | apply HomEquiv.trans (HomEquiv.comp (by hom_close) (HomEquiv.comp (by rfl) (by rfl)))
--         | apply HomEquiv.trans (HomEquiv.comp (HomEquiv.comp (by hom_close) (by rfl)) (by rfl))
--         | apply HomEquiv.trans (HomEquiv.comp (HomEquiv.comp (by rfl) (by hom_close)) (by rfl))
--         | apply HomEquiv.trans (HomEquiv.comp (HomEquiv.comp (by rfl) (by rfl)) (by hom_close))
--       ))
  -- )

-- idea: do a closing goal OR do a symm then a closing goal

-- macro "hom_equiv" : tactic =>
--   `(tactic|
--     repeat
--       first
--         -- closing goals
--         | apply HomEquiv.refl
--         | apply HomEquiv.comp_id
--         | apply HomEquiv.id_comp
--         | apply HomEquiv.assoc
--         | apply HomEquiv.id_tensor_id
--         | apply HomEquiv.tensor_comp_tensor
--         | apply HomEquiv.tensor_assoc
--         | apply HomEquiv.id_tensor
--         | apply HomEquiv.tensor_id
--         -- congruences
--         | apply HomEquiv.comp <;> assumption
--         | apply HomEquiv.tensor <;> assumption
--         -- meta rules
--         | (apply HomEquiv.symm; assumption)
--         | (apply HomEquiv.trans; assumption)
--   )

@[simp]
lemma HomEquiv.whiskerLeft (X : S V) {Y Z} {f f' : Y ⟶ Z} (h : f ≈ f') :
    (X ◁ f) ≈ (X ◁ f') := by grind

@[simp]
lemma HomEquiv.whiskerRight {X Y} {f f' : X ⟶ Y} (Z : S V) (h : HomEquiv f f') :
    HomEquiv (f ▷ Z) (f' ▷ Z) := by grind
  -- simp
  -- -- simp
  -- -- hom_close_symm
  -- -- rfl
  -- -- apply hi'
  -- -- apply hi''
  -- -- apply HomEquiv.trans (by hom_cong)
  -- -- symm
  -- apply HomEquiv.trans (by hom_cong)
  -- -- focus apply HomEquiv.trans
  -- -- · focus apply HomEquiv.tensor ?_ (by rfl)
  --   -- focusN 2



  --   -- case blah =>
  --   --   assumption

  -- · sorry





  -- · sorry

  -- apply HomEquiv.trans
  -- · sorry



-- @[simp]
-- lemma test {X₁ Y₁ X₂ Y₂ : S V} (f₁ : X₁ ⟶ Y₁) (f₂ : X₂ ⟶ Y₂) (g₁ : Y₁ ⟶ Z₁) (g₂ : Y₂ ⟶ Z₂) (x : (X₁ * X₂) ⟶ (Z₁ * Z₂)) : HomEquiv ((f₁ ⊗ f₂) ≫ (g₁ ⊗ g₂)) x ↔ HomEquiv ((f₁ ≫ g₁) ⊗ (f₂ ≫ g₂)) x := by
--   constructor
--   · intro h
--     trans
--     · symm
--       apply HomEquiv.tensor_comp_tensor
--     · exact h
--   · intro h
--     trans
--     · apply HomEquiv.tensor_comp_tensor
--     · exact h

-- attribute [grind .] HomEquiv.tensor_comp_tensor
-- attribute [grind] HomEquiv.tensor_comp_tensor

@[simp, grind .]
lemma HomEquiv.tensorHom_def {X₁ Y₁ X₂ Y₂ : S V} (f : X₁ ⟶ Y₁) (g : X₂ ⟶ Y₂) :
    HomEquiv (f ⊗ g) (f ▷ X₂ ≫ Y₁ ◁ g) := by
  simp
  symm
  grind [tensor_comp_tensor]

  -- · tensor_comp_tensor
  -- grind
  -- have h : HomEquiv g g := by
  --   hom_equiv
  -- apply HomEquiv.trans (by hom_close)
  -- hom_equiv
  -- hom_equiv
  -- try (apply HomEquiv.trans (by hom_close))
  -- sorry

  -- hom_equiv

  -- simp
  -- hom_close_symm
  -- rfl
  -- apply hi'
  -- apply hi''
  -- symm
  -- hom_equiv
  -- hom_equiv
  -- hom_equiv

  -- have h : HomEquiv (f ⊗ g) ?_ := by
  --   hom_close


  --   sorry
  -- apply HomEquiv.trans sorry

  -- · hom_close
  --   sorry
  -- try apply HomEquiv.trans (by hom_close)
  -- (first
  --       | simp
  --       -- | trace_state
  --       -- closing goals
  --       | hom_close_symm
  --       | rfl

  --       -- unary
  --       | apply hi'
  --       | apply hi''

  --       -- congruences (recursive)
  --       -- | apply HomEquiv.comp
  --       -- | apply HomEquiv.tensor

  --       -- meta rules (recursive)
  --       | apply HomEquiv.trans (by hom_close)
  --       | symm; apply HomEquiv.trans (by hom_close)
  --     )
  -- symm; apply HomEquiv.trans (by hom_close)

  -- apply HomEquiv.trans (by hom_close)
  -- hom_close

  -- hom_equiv
  -- hom_close
  -- hom_close
  -- hom_close
  -- hom_close
  -- (repeat' (first
  --       -- closing goals
  --       | assumption
  --       | apply HomEquiv.comp_id
  --       | apply HomEquiv.id_comp
  --       | apply HomEquiv.assoc
  --       | apply HomEquiv.id_tensor_id
  --       | apply HomEquiv.tensor_comp_tensor
  --       | apply HomEquiv.tensor_assoc
  --       | apply HomEquiv.id_tensor
  --       | apply HomEquiv.tensor_id
  --       | apply hi'
  --       | apply hi''
  --       | apply HomEquiv.comp (by rfl) ?_
  --       | apply HomEquiv.comp ?_ (by rfl)
  --       | apply HomEquiv.tensor (by rfl) ?_
  --       | apply HomEquiv.tensor ?_ (by rfl)
  --     ))
  -- sorry
  -- hom_equiv
  -- simp
  -- symm
  -- apply HomEquiv.trans
  -- · hom_close_symm
  -- ·


@[simp, grind]
lemma HomEquiv.whiskerLeft_id (X Y : S V) : HomEquiv (X ◁ (𝟙 Y)) (𝟙 (X * Y)) := by
  grind

-- | whiskerLeft_id (X Y) : HomEquiv ((Hom.id Y).whiskerLeft X) (Hom.id (X.tensor Y))
-- | id_whiskerRight (X Y) : HomEquiv ((Hom.id X).whiskerRight Y) (Hom.id (X.tensor Y))
@[simp, grind]
lemma HomEquiv.id_whiskerRight (X Y : S V) : HomEquiv ((𝟙 X) ▷ Y) (𝟙 (X * Y)) := by
  grind

instance setoidHom (X Y : S V) : Setoid (X ⟶ Y) :=
⟨HomEquiv, ⟨HomEquiv.refl, HomEquiv.symm _ _, HomEquiv.trans⟩⟩

def myHom (X Y : S V) := Quotient (setoidHom X Y)

@[grind =_]
lemma myHom_eq {X Y : S V} (f g : X ⟶ Y) : HomEquiv f g ↔ f ≈ g := by
  constructor
  all_goals intros h
  all_goals exact h

open HomEquiv

-- def StrictMonoidalProduct' (X : Type u) := List X

-- notation "S' " => StrictMonoidalProduct'

-- instance : Monoid (S' V) where
--   one := []
--   mul := List.append
--   mul_assoc := List.append_assoc
--   one_mul := List.nil_append
--   mul_one := List.append_nil

@[simp]
instance hi : Category (S V) where
  Hom X Y := myHom X Y
  id X := ⟦𝟙 X⟧
  comp f g := Quotient.map₂ (· ≫ ·) (fun _ _ hf _ _ hg ↦ HomEquiv.comp hf hg) f g
  id_comp {X Y} := by
    rintro ⟨f⟩
    apply Quotient.sound
    grind
  comp_id {X Y} := by
    rintro ⟨f⟩
    apply Quotient.sound
    grind
  assoc {W X Y Z} := by
    rintro ⟨f⟩ ⟨g⟩ ⟨h⟩
    apply Quotient.sound
    grind

-- @[simp]
-- theorem eqToHom_awesome [CategoryStruct C] {X Y : C} (p : X = Y) (q : Y = X) :
--     eqToHom p ≫ eqToHom q = 𝟙 X ≫ 𝟙 X := by
--   cases p
--   cases q
--   simp

instance : MonoidalCategory (S V) where
  tensorObj X Y := X * Y
  tensorHom f g := Quotient.map₂ (· ⊗ ·) (fun _ _ hf _ _ hg ↦ HomEquiv.tensor hf hg) f g
  tensorUnit := 1
  associator X Y Z := {
    hom := ⟦eqToHom (by simp [mul_assoc])⟧ -- Quotient.mk (eqToHom (mul_assoc X Y Z)),
    inv := ⟦eqToHom (by simp [mul_assoc])⟧ -- Quotient.mk (eqToHom (mul_assoc X Y Z)),
    hom_inv_id := by
      apply Quotient.sound
      simp
      apply eqToHom_comp
    inv_hom_id := by
      apply Quotient.sound
      apply eqToHom_comp
  }
  leftUnitor X := {
    hom := ⟦eqToHom (by simp [one_mul])⟧, -- TODO: not tactic mode, just exactly the lemma?
    inv := ⟦eqToHom (by simp [one_mul])⟧,
    hom_inv_id := by
      apply Quotient.sound
      apply eqToHom_comp
    inv_hom_id := by
      apply Quotient.sound
      apply eqToHom_comp
  }
  rightUnitor X := {
    hom := ⟦eqToHom (by simp [mul_one])⟧,
    inv := ⟦eqToHom (by simp [mul_one])⟧,
    hom_inv_id := by
      apply Quotient.sound
      apply eqToHom_comp
    inv_hom_id := by
      apply Quotient.sound
      apply eqToHom_comp
  }
  whiskerLeft X {Y₁ Y₂} f := Quotient.map (X ◁ ·) (fun _ _ hf ↦ HomEquiv.whiskerLeft X hf) f
  whiskerRight {X₁ X₂} f Y := Quotient.map (· ▷ Y) (fun _ _ hf ↦ HomEquiv.whiskerRight Y hf) f
  tensorHom_def {X₁ Y₁ X₂ Y₂} := by
    rintro ⟨f⟩ ⟨g⟩
    apply Quotient.sound
    grind
  id_tensorHom_id _ _ := Quotient.sound id_tensor_id
  tensorHom_comp_tensorHom {X₁ Y₁ Z₁ X₂ Y₂ Z₂} := by
    rintro ⟨f₁⟩ ⟨f₂⟩ ⟨g₁⟩ ⟨g₂⟩
    apply Quotient.sound
    grind
  whiskerLeft_id X Y := Quotient.sound (HomEquiv.whiskerLeft_id X Y)
  id_whiskerRight X Y := Quotient.sound (HomEquiv.id_whiskerRight X Y)
  associator_naturality {X₁ X₂ X₃ Y₁ Y₂ Y₃} := by
    rintro ⟨f₁⟩ ⟨f₂⟩ ⟨f₃⟩
    apply Quotient.sound
    grind
  leftUnitor_naturality {X Y} := by
    rintro ⟨f⟩
    apply Quotient.sound
    grind
  rightUnitor_naturality {X Y} := by
    rintro ⟨f⟩
    apply Quotient.sound
    grind
  pentagon W X Y Z := by
    apply Quotient.sound
    simp
    trans
    · apply HomEquiv.comp
      · apply eqToHom_tensor
        rfl
      · apply HomEquiv.trans
        · apply HomEquiv.comp
          · rfl
          · apply eqToHom_tensor
            rfl
        · apply eqToHom_comp
    · grind [eqToHom_tensor, eqToHom_comp]
  triangle X Y := by
    simp
    apply Quotient.sound
    trans
    · trans
      · apply HomEquiv.comp
        · rfl
        · apply eqToHom_tensor
          rfl
      · apply eqToHom_comp
    · symm
      apply eqToHom_tensor
      rfl
