import Mathlib
import LeanCategory.FusedBraids.ToFusedBraids
import LeanCategory.FusedBraids.FromFusedBraids

namespace CategoryTheory.FusedBraids

open FreeTwistedCategoryQuiver

open CategoryTheory MonoidalCategory InvolutiveCategory TwistedCategory

variable {C : Type u} [Category.{v} C] {D : Type u'} [Category.{v'} D]
variable {F : C ⥤ D} {G : D ⥤ C}

/--
If we have decidable equality on the morphisms in C, we can carry that decidability through
to morphisms in D as long as functors between them compose to the identity:
-/
def decidable_carry {X Y : D} (decider : DecidableEq (G.obj X ⟶ G.obj Y)) (h : G ⋙ F = 𝟭 D) :
    DecidableEq (X ⟶ Y) := by
  intros f g
  have decided := decider (G.map f) (G.map g)
  cases decided
  case isTrue eq =>
    apply isTrue
    have eq' : (G ⋙ F).map f = (G ⋙  F).map g := by
      simp
      rw [eq]
    rw [h] at eq'
    exact eq'
  case isFalse neq =>
    apply isFalse
    intros hfalse
    rw [hfalse] at neq
    simp at neq

/-
Future work: mapping a morphism in the free twisted category generated
by a quiver to fused braids and back again is the identity
-/
variable (comp_eq : toFusedBraids ⋙ fromFusedBraids = 𝟭 (TQ C))

/-
Pen-and-paper proof from our paper: fused braids have decidable
equality (crucially, polytime decidable equality!)
-/
variable (paper_result : ∀ X Y : (FB C), DecidableEq (X ⟶ Y))

/--
Assuming decidable equality on fused braids and that the
functors compose to the identity, we get decidable equality on the morphisms in the
free twisted category generated by a quiver
-/
def TQ_decider : ∀ X Y : TQ C, DecidableEq (X ⟶ Y) := fun X Y ↦
  decidable_carry (paper_result (toFusedBraids.obj X) (toFusedBraids.obj Y)) comp_eq

end CategoryTheory.FusedBraids

