import Mathlib

/-!
# Monoidal words

This file defines the formal "tensor words" used as objects of the braid
groupoid: a free magma with a unit generated by a type of labels.
-/

universe u

namespace BraidGroupoid

/--
A formal tensor word on a type of labels.

This is the free monoid object in the language of a monoidal category: it is
built from labels using a unit and a binary tensor.
-/
inductive MonoidalWord (α : Type u) : Type u
    | of : α → MonoidalWord α
    | unit : MonoidalWord α
    | tensor : MonoidalWord α → MonoidalWord α → MonoidalWord α
    deriving Inhabited, Repr

/-- A label assignment for a fixed tensor-word shape. -/
inductive MonoidalWord.Match (β : Type u) : MonoidalWord α → Type u
    | unit : MonoidalWord.Match β .unit
    | of {a : α} (b : β) : MonoidalWord.Match β (.of a)
    | tensor {X Y} (mx : MonoidalWord.Match β X) (my : MonoidalWord.Match β Y) :
        MonoidalWord.Match β (.tensor X Y)

/-- Recover the tensor word over labels from a shape assignment. -/
def MonoidalWord.Match.toMonoidalWord : MonoidalWord.Match β X → MonoidalWord β
    | unit => .unit
    | of b => .of b
    | tensor mx my => .tensor mx.toMonoidalWord my.toMonoidalWord

/--
Map labels through a partial function, dropping labels sent to `none`.
-/
def MonoidalWord.project (f : α → Option β) : MonoidalWord α → MonoidalWord β
    | MonoidalWord.unit => .unit
    | MonoidalWord.of a =>
        match f a with
        | some b => .of b
        | none => .unit
    | MonoidalWord.tensor x y => .tensor (x.project f) (y.project f)

end BraidGroupoid
