import Mathlib

/-!
# Monoidal words

This file defines the formal "tensor words" used as objects of the braid
groupoid: a free magma with a unit generated by a type of labels.
-/

universe u

namespace BraidGroupoid

/--
A formal tensor word on a type of labels.

This is the free monoid object in the language of a monoidal category: it is
built from labels using a unit and a binary tensor.
-/
inductive MonoidalWord (α : Type u) : Type u
    | of : α → MonoidalWord α
    | unit : MonoidalWord α
    | tensor : MonoidalWord α → MonoidalWord α → MonoidalWord α
    deriving Inhabited, Repr

/-- A label assignment for a fixed tensor-word shape. -/
inductive MonoidalWord.Match (β : Type u) : MonoidalWord α → Type u
    | unit : MonoidalWord.Match β .unit
    | of {a : α} (b : β) : MonoidalWord.Match β (.of a)
    | tensor {X Y} (mx : MonoidalWord.Match β X) (my : MonoidalWord.Match β Y) :
        MonoidalWord.Match β (.tensor X Y)

/-- The only match on `unit` is `unit`. -/
@[simp]
lemma MonoidalWord.Match.match_unit (A : MonoidalWord.Match β (.unit : MonoidalWord α)) :
    A = .unit := by
  cases A
  rfl

/-- A match on `of` is determined by a label. -/
lemma MonoidalWord.Match.match_of (A : MonoidalWord.Match β (.of a)) : ∃ b, A = .of b := by
  cases A
  simp

/-- A match on `tensor` splits into matches on each tensor factor. -/
lemma MonoidalWord.Match.match_tensor (A : MonoidalWord.Match β (.tensor X Y)) :
    ∃ B C, A = .tensor B C := by
  cases A
  simp

/-!
## Tactic support for `MonoidalWord.Match`
-/

/--
Destruct a `MonoidalWord.Match` term by repeatedly applying `match_unit`,
`match_of`, and `match_tensor`, rewriting the goal via `subst`.

Usage:
```
match_simplify A
```
-/
syntax (name := match_simplify) "match_simplify " ident : tactic

macro_rules
  | `(tactic| match_simplify $A) =>
      `(tactic|
        first
          | have h := MonoidalWord.Match.match_unit (A := $A); subst $A
          | obtain ⟨b, h⟩ := MonoidalWord.Match.match_of (A := $A); subst $A
          | obtain ⟨A1, A2, h⟩ := MonoidalWord.Match.match_tensor (A := $A)
            subst $A
            try match_simplify A1
            try match_simplify A2
          | fail "match_simplify failed: no applicable match lemmas"
      )

/-- Recover the tensor word over labels from a shape assignment. -/
def MonoidalWord.Match.toMonoidalWord : MonoidalWord.Match β X → MonoidalWord β
    | unit => .unit
    | of b => .of b
    | tensor mx my => .tensor mx.toMonoidalWord my.toMonoidalWord

/--
Map labels through a partial function, dropping labels sent to `none`.
-/
def MonoidalWord.project (f : α → Option β) : MonoidalWord α → MonoidalWord β
    | MonoidalWord.unit => .unit
    | MonoidalWord.of a =>
        match f a with
        | some b => .of b
        | none => .unit
    | MonoidalWord.tensor x y => .tensor (x.project f) (y.project f)

end BraidGroupoid
