import Mathlib

/-!
# Monoidal words

This file defines the formal "tensor words" used as objects of the braid
groupoid: a free magma with a unit generated by a type of labels.
-/

universe u

/--
A formal tensor word on a type of labels.

This is the free monoid object in the language of a monoidal category: it is
built from labels using a unit and a binary tensor.
-/
inductive MonoidalWord (α : Type u) : Type u
    | of : α → MonoidalWord α
    | unit : MonoidalWord α
    | tensor : MonoidalWord α → MonoidalWord α → MonoidalWord α
    deriving Inhabited, Repr

instance : Mul (MonoidalWord α) where
    mul := MonoidalWord.tensor

instance : One (MonoidalWord α) where
    one := MonoidalWord.unit

instance : Coe α (MonoidalWord α) where
    coe := MonoidalWord.of

def MonoidalWord.Positive : MonoidalWord α → Prop
    | .of _ => True
    | .unit => False
    | .tensor x y => x.Positive ∨ y.Positive

/-- Monoidal words that aren't the identity -/
def PMonoidalWord (α) := { m : MonoidalWord α // m.Positive }

@[coe]
def PMonoidalWord.val : PMonoidalWord α → MonoidalWord α := Subtype.val

instance coePMonoidalWordMonoidalWord : Coe (PMonoidalWord α) (MonoidalWord α) :=
  ⟨PMonoidalWord.val⟩

instance [Repr α] : Repr (PMonoidalWord α) where
  reprPrec m prec := reprPrec m.val prec

@[inherit_doc]
notation "MonoidalWord+" => PMonoidalWord

/-- A label assignment for a fixed tensor-word shape. -/
inductive MonoidalWord.Match (β : Type u) : MonoidalWord α → Type u
    | unit : MonoidalWord.Match β .unit
    | of {a : α} (b : β) : MonoidalWord.Match β (.of a)
    | tensor {X Y} (mx : MonoidalWord.Match β X) (my : MonoidalWord.Match β Y) :
        MonoidalWord.Match β (.tensor X Y)

instance : HMul (MonoidalWord.Match β X) (MonoidalWord.Match β Y) (MonoidalWord.Match β (.tensor X Y)) where
    hMul := MonoidalWord.Match.tensor

instance : One (MonoidalWord.Match β (α := α) .unit) where
    one := MonoidalWord.Match.unit

/-- The only match on `unit` is `unit`. -/
@[simp]
lemma MonoidalWord.Match.match_unit (A : MonoidalWord.Match β (.unit : MonoidalWord α)) :
    A = .unit := by
  cases A
  rfl

/-- A match on `of` is determined by a label. -/
lemma MonoidalWord.Match.match_of (A : MonoidalWord.Match β (.of a)) : ∃ b, A = .of b := by
  cases A
  simp

/-- A match on `tensor` splits into matches on each tensor factor. -/
lemma MonoidalWord.Match.match_tensor (A : MonoidalWord.Match β (.tensor X Y)) :
    ∃ B C, A = .tensor B C := by
  cases A
  simp

/-!
## Tactic support for `MonoidalWord.Match`
-/

/--
Destruct a `MonoidalWord.Match` term by repeatedly applying `match_unit`,
`match_of`, and `match_tensor`, rewriting the goal via `subst`.

Usage:
```
match_simplify A
```
-/
syntax (name := match_simplify) "match_simplify " ident : tactic

macro_rules
  | `(tactic| match_simplify $A) =>
      `(tactic|
        first
          | have h := MonoidalWord.Match.match_unit (A := $A); subst $A
          | obtain ⟨b, h⟩ := MonoidalWord.Match.match_of (A := $A); subst $A
          | obtain ⟨A1, A2, h⟩ := MonoidalWord.Match.match_tensor (A := $A)
            subst $A
            try match_simplify A1
            try match_simplify A2
          | fail "match_simplify failed: no applicable match lemmas"
      )

/-- Recover the tensor word over labels from a shape assignment. -/
def MonoidalWord.Match.toMonoidalWord : MonoidalWord.Match β X → MonoidalWord β
    | unit => .unit
    | of b => .of b
    | tensor mx my => .tensor mx.toMonoidalWord my.toMonoidalWord

def MonoidalWord.reverse : MonoidalWord α → MonoidalWord α
    | .unit => .unit
    | .of a => .of a
    | .tensor x y => .tensor y.reverse x.reverse

def MonoidalWord.map (f : α → MonoidalWord β) : MonoidalWord α → MonoidalWord β
    | unit => .unit
    | of a => f a
    | tensor x y => .tensor (x.map f) (y.map f)

/--
Map labels through a partial function, dropping labels sent to `none`.
-/
def MonoidalWord.project (f : α → Option β) : MonoidalWord α → MonoidalWord β :=
    MonoidalWord.map (fun a =>
        match f a with
        | some b => .of b
        | none => .unit)

inductive MonoidalWord.equiv : MonoidalWord α → MonoidalWord α → Prop
  | refl X : MonoidalWord.equiv X X
  | comp_id : MonoidalWord.equiv (x * 1) x
  | id_comp : MonoidalWord.equiv (1 * x) x
  | assoc : MonoidalWord.equiv ((x * y) * z) (x * (y * z))
  | symm (h : MonoidalWord.equiv X Y) : MonoidalWord.equiv Y X
  | trans (h₁ : MonoidalWord.equiv X Y) (h₂ : MonoidalWord.equiv Y Z) : MonoidalWord.equiv X Z

instance : HasEquiv (MonoidalWord α) where
  Equiv := MonoidalWord.equiv

@[refl]
def MonoidalWord.equiv.refl' {X : MonoidalWord α} : X ≈ X := .refl X

@[symm]
def MonoidalWord.equiv.symm' {X Y : MonoidalWord α} (h : X ≈ Y) : Y ≈ X := .symm h

instance : Trans (MonoidalWord.equiv (α := α)) (MonoidalWord.equiv) (MonoidalWord.equiv) where
  trans := MonoidalWord.equiv.trans

instance : Equivalence (MonoidalWord.equiv (α := α)) where
  refl := MonoidalWord.equiv.refl
  symm := MonoidalWord.equiv.symm
  trans := MonoidalWord.equiv.trans
