import Mathlib
import LeanCategory.MonoidalWord

/-!
# Braid groupoid morphisms

This file defines the formal generators for morphisms in the braid groupoid.
-/

universe u

namespace BraidGroupoid

/-- Formal braids generated by crossings, associators, and unitors. -/
inductive Hom {α : Type u} : MonoidalWord α → MonoidalWord α → Type u
    | id (X : MonoidalWord α) : Hom X X
    | α_hom (X Y Z : MonoidalWord α) : Hom ((X.tensor Y).tensor Z) (X.tensor (Y.tensor Z))
    | α_inv (X Y Z : MonoidalWord α) : Hom (X.tensor (Y.tensor Z)) ((X.tensor Y).tensor Z)
    | l_hom (X) : Hom (MonoidalWord.unit.tensor X) X
    | l_inv (X) : Hom X (MonoidalWord.unit.tensor X)
    | ρ_hom (X) : Hom (X.tensor MonoidalWord.unit) X
    | ρ_inv (X) : Hom X (X.tensor MonoidalWord.unit)
    | σ_hom (X Y : MonoidalWord α) : Hom (X.tensor Y) (Y.tensor X)
    | σ_inv (X Y : MonoidalWord α) : Hom (Y.tensor X) (X.tensor Y)
    | comp {X Y Z} (f : Hom X Y) (g : Hom Y Z) : Hom X Z
    -- | whiskerLeft (X : MonoidalWord α) {Y₁ Y₂} (f : Hom Y₁ Y₂) : Hom (X.tensor Y₁) (X.tensor Y₂)
    -- | whiskerRight {X₁ X₂} (f : Hom X₁ X₂) (Y : MonoidalWord α) :
        -- Hom (X₁.tensor Y) (X₂.tensor Y)
    | tensor {W X Y Z} (f : Hom W Y) (g : Hom X Z) : Hom (W.tensor X) (Y.tensor Z)

/-- Notation for braid morphisms. -/
scoped[ BraidGroupoid ] infixr:10 " ⟶ᵇ " => Hom

instance : HMul (X₁ ⟶ᵇ Y₁) (X₂ ⟶ᵇ Y₂) (X₁ * X₂ ⟶ᵇ Y₁ * Y₂) where
    hMul := .tensor

instance : One (X ⟶ᵇ X) where
    one := .id X

/-- Left whiskering by tensoring with identity. -/
@[simp]
def Hom.whiskerLeft (X : MonoidalWord α) {Y₁ Y₂} (f : Y₁ ⟶ᵇ Y₂) : X.tensor Y₁ ⟶ᵇ X.tensor Y₂ :=
    (1 : X ⟶ᵇ X) * f

/-- Right whiskering by tensoring with identity. -/
@[simp]
def Hom.whiskerRight {X₁ X₂} (f : X₁ ⟶ᵇ X₂) (Y : MonoidalWord α) :
        X₁.tensor Y ⟶ᵇ X₂.tensor Y :=
    f * (1 : Y ⟶ᵇ Y)

open scoped BraidGroupoid

/-- Transport a shape assignment along a braid morphism. -/
@[simp]
def Hom.transport {α β : Type u} {X Y : MonoidalWord α} :
    (X ⟶ᵇ Y) → MonoidalWord.Match (α := α) β X → MonoidalWord.Match (α := α) β Y
    | .id _, A => A
    | .α_hom _ _ _, .tensor (.tensor A B) C => .tensor A (.tensor B C)
    | .α_inv _ _ _, .tensor A (.tensor B C) => .tensor (.tensor A B) C
    | .l_hom _, .tensor .unit A => A
    | .l_inv _, A => .tensor .unit A
    | .ρ_hom _, .tensor A .unit => A
    | .ρ_inv _, A => .tensor A .unit
    | .σ_hom _ _, .tensor A B => .tensor B A
    | .σ_inv _ _, .tensor B A => .tensor A B
    | .comp f g, A => g.transport  (f.transport A)
    | .tensor f g, .tensor A B => .tensor (f.transport A) (g.transport B)

/-- The codomain word induced by `Hom.transport`. -/
def Hom.newCod {α β : Type u} {X Y : MonoidalWord α} :
    (X ⟶ᵇ Y) → MonoidalWord.Match (α := α) β X → MonoidalWord β
    | f, A => (Hom.transport f A).toMonoidalWord

/-- Enrich a braid morphism by replacing its labels with a chosen assignment. -/
def Hom.enrich {α β : Type u} {X Y : MonoidalWord α} :
    (f : X ⟶ᵇ Y) →
      (A : MonoidalWord.Match (α := α) β X) →
        (A.toMonoidalWord ⟶ᵇ f.newCod A)
    | .id _, A => .id (A.toMonoidalWord)
    | .α_hom _ _ _, .tensor (.tensor A B) C =>
        .α_hom A.toMonoidalWord B.toMonoidalWord C.toMonoidalWord
    | .α_inv _ _ _, .tensor A (.tensor B C) =>
        .α_inv A.toMonoidalWord B.toMonoidalWord C.toMonoidalWord
    | .l_hom _, .tensor .unit A => .l_hom A.toMonoidalWord
    | .l_inv _, A => .l_inv A.toMonoidalWord
    | .ρ_hom _, .tensor A .unit => .ρ_hom A.toMonoidalWord
    | .ρ_inv _, A => .ρ_inv A.toMonoidalWord
    | .σ_hom _ _, .tensor A B => .σ_hom A.toMonoidalWord B.toMonoidalWord
    | .σ_inv _ _, .tensor B A => .σ_inv A.toMonoidalWord B.toMonoidalWord
    | .comp f g, A =>
        .comp (Hom.enrich f A) (Hom.enrich g (Hom.transport f A))
    | .tensor f g, .tensor A B =>
        .tensor (Hom.enrich f A) (Hom.enrich g B)

/-- Inverse on generators, reversing composition. -/
@[simp]
def Hom.inv {α : Type u} {X Y : MonoidalWord α} : Hom X Y → Hom Y X
    | .id X => .id X
    | .α_hom X Y Z => .α_inv X Y Z
    | .α_inv X Y Z => .α_hom X Y Z
    | .l_hom X => .l_inv X
    | .l_inv X => .l_hom X
    | .ρ_hom X => .ρ_inv X
    | .ρ_inv X => .ρ_hom X
    | .σ_hom X Y => .σ_inv X Y
    | .σ_inv X Y => .σ_hom X Y
    | .comp f g => .comp g.inv f.inv
    | .tensor f g => .tensor f.inv g.inv

end BraidGroupoid
