import Mathlib
import LeanCategory.Egger

/- Given a quiver over a monoid, construct the free twisted involutive monoidal category
generated by that quiver -/

namespace CategoryTheory

variable {C : Type u}

section

variable (C : Type u)

inductive FreeTwistedCategory : Type u
  | of : C → FreeTwistedCategory
  | unit : FreeTwistedCategory
  | tensor : FreeTwistedCategory → FreeTwistedCategory → FreeTwistedCategory
  | star : FreeTwistedCategory → FreeTwistedCategory
  deriving Inhabited

end

namespace FreeTwistedCategory

notation "F" => FreeTwistedCategory

@[simp]
instance : MulOne (F C) where
  one := unit
  mul := tensor

@[simp]
instance : Star (F C) where
  star := star

inductive Hom : F C → F C → Type max u v
  | id (X) : Hom X X
  | comp {X Y Z} (f : Hom X Y) (g : Hom Y Z) : Hom X Z
  | whiskerLeft (X : F C) {Y₁ Y₂} (f : Hom Y₁ Y₂) : Hom (X.tensor Y₁) (X.tensor Y₂)
  | whiskerRight {X₁ X₂} (f : Hom X₁ X₂) (Y : F C) : Hom (X₁.tensor Y) (X₂.tensor Y)
  | tensor {W X Y Z} (f : Hom W Y) (g : Hom X Z) : Hom (W.tensor X) (Y.tensor Z)
  | α_hom (X Y Z : F C) : Hom ((X * Y) * Z) (X * (Y * Z))
  | α_inv (X Y Z : F C) : Hom (X * (Y * Z)) ((X * Y) * Z)
  | l_hom (X) : Hom (1 * X) X
  | l_inv (X) : Hom X (1 * X)
  | ρ_hom (X : F C) : Hom (X * 1) X
  | ρ_inv (X : F C) : Hom X (X * 1)
  | star {X Y} (f : Hom X Y) : Hom X.star Y.star
  | χ_hom (X Y : F C) : Hom (X.star * Y.star) (Y * X).star
  | χ_inv (X Y : F C) : Hom (Y * X).star (X.star * Y.star)
  | ε_hom (X : F C) : Hom X.star.star X
  | ε_inv (X : F C) : Hom X X.star.star
  | twist_hom (X : F C) : Hom X.star X
  | twist_inv (X : F C) : Hom X X.star

infixr:10 " ⟶ᵐ " => Hom
-- TODO notation for 𝟙ᵐ, ≫ᵐ

@[simp]
def Hom.inv {X Y : F C} : (X ⟶ᵐ Y) → (Y ⟶ᵐ X)
  | id X => id X
  | comp f g => comp (g.inv) (f.inv)
  | whiskerLeft X f => whiskerLeft X (f.inv)
  | whiskerRight f Y => whiskerRight (f.inv) Y
  | tensor f g => tensor (f.inv) (g.inv)
  | α_hom X Y Z => α_inv X Y Z
  | α_inv X Y Z => α_hom X Y Z
  | l_hom X => l_inv X
  | l_inv X => l_hom X
  | ρ_hom X => ρ_inv X
  | ρ_inv X => ρ_hom X
  | star f => star (f.inv)
  | χ_hom X Y => χ_inv X Y
  | χ_inv X Y => χ_hom X Y
  | ε_hom X => ε_inv X
  | ε_inv X => ε_hom X
  | twist_hom X => twist_inv X
  | twist_inv X => twist_hom X

inductive HomEquiv : ∀ {X Y : F C}, (X ⟶ᵐ Y) → (X ⟶ᵐ Y) → Prop
  | refl {X Y} (f : X ⟶ᵐ Y) : HomEquiv f f
  | symm {X Y} (f g : X ⟶ᵐ Y) : HomEquiv f g → HomEquiv g f
  | trans {X Y} {f g h : X ⟶ᵐ Y} : HomEquiv f g → HomEquiv g h → HomEquiv f h
  | comp {X Y Z} {f f' : X ⟶ᵐ Y} {g g' : Y ⟶ᵐ Z} :
      HomEquiv f f' → HomEquiv g g' → HomEquiv (f.comp g) (f'.comp g')
  | whiskerLeft (X) {Y Z} (f f' : Y ⟶ᵐ Z) :
      HomEquiv f f' → HomEquiv (f.whiskerLeft X) (f'.whiskerLeft X)
  | whiskerRight {Y Z} (f f' : Y ⟶ᵐ Z) (X) :
      HomEquiv f f' → HomEquiv (f.whiskerRight X) (f'.whiskerRight X)
  | tensor {W X Y Z} {f f' : W ⟶ᵐ X} {g g' : Y ⟶ᵐ Z} :
      HomEquiv f f' → HomEquiv g g' → HomEquiv (f.tensor g) (f'.tensor g')
  | tensorHom_def {X₁ Y₁ X₂ Y₂} (f : X₁ ⟶ᵐ Y₁) (g : X₂ ⟶ᵐ Y₂) :
      HomEquiv (f.tensor g) ((f.whiskerRight X₂).comp (g.whiskerLeft Y₁))
  | comp_id {X Y} (f : X ⟶ᵐ Y) : HomEquiv (f.comp (Hom.id _)) f
  | id_comp {X Y} (f : X ⟶ᵐ Y) : HomEquiv ((Hom.id _).comp f) f
  | assoc {X Y U V : F C} (f : X ⟶ᵐ U) (g : U ⟶ᵐ V) (h : V ⟶ᵐ Y) :
      HomEquiv ((f.comp g).comp h) (f.comp (g.comp h))
  | id_tensorHom_id {X Y} : HomEquiv ((Hom.id X).tensor (Hom.id Y)) (Hom.id _)
  | tensorHom_comp_tensorHom {X₁ Y₁ Z₁ X₂ Y₂ Z₂ : F C} (f₁ : X₁ ⟶ᵐ Y₁) (f₂ : X₂ ⟶ᵐ Y₂)
      (g₁ : Y₁ ⟶ᵐ Z₁) (g₂ : Y₂ ⟶ᵐ Z₂) :
    HomEquiv ((f₁.tensor f₂).comp (g₁.tensor g₂)) ((f₁.comp g₁).tensor (f₂.comp g₂))
  | whiskerLeft_id (X Y) : HomEquiv ((Hom.id Y).whiskerLeft X) (Hom.id (X.tensor Y))
  | id_whiskerRight (X Y) : HomEquiv ((Hom.id X).whiskerRight Y) (Hom.id (X.tensor Y))
  | α_hom_inv {X Y Z} : HomEquiv ((Hom.α_hom X Y Z).comp (Hom.α_inv X Y Z)) (Hom.id _)
  | α_inv_hom {X Y Z} : HomEquiv ((Hom.α_inv X Y Z).comp (Hom.α_hom X Y Z)) (Hom.id _)
  | associator_naturality {X₁ X₂ X₃ Y₁ Y₂ Y₃} (f₁ : X₁ ⟶ᵐ Y₁) (f₂ : X₂ ⟶ᵐ Y₂) (f₃ : X₃ ⟶ᵐ Y₃) :
      HomEquiv (((f₁.tensor f₂).tensor f₃).comp (Hom.α_hom Y₁ Y₂ Y₃))
        ((Hom.α_hom X₁ X₂ X₃).comp (f₁.tensor (f₂.tensor f₃)))
  | ρ_hom_inv {X} : HomEquiv ((Hom.ρ_hom X).comp (Hom.ρ_inv X)) (Hom.id _)
  | ρ_inv_hom {X} : HomEquiv ((Hom.ρ_inv X).comp (Hom.ρ_hom X)) (Hom.id _)
  | ρ_naturality {X Y} (f : X ⟶ᵐ Y) :
      HomEquiv ((f.whiskerRight unit).comp (Hom.ρ_hom Y)) ((Hom.ρ_hom X).comp f)
  | l_hom_inv {X} : HomEquiv ((Hom.l_hom X).comp (Hom.l_inv X)) (Hom.id _)
  | l_inv_hom {X} : HomEquiv ((Hom.l_inv X).comp (Hom.l_hom X)) (Hom.id _)
  | l_naturality {X Y} (f : X ⟶ᵐ Y) :
      HomEquiv ((f.whiskerLeft unit).comp (Hom.l_hom Y)) ((Hom.l_hom X).comp f)
  | pentagon {W X Y Z} :
      HomEquiv
        (((Hom.α_hom W X Y).whiskerRight Z).comp
          ((Hom.α_hom W (X.tensor Y) Z).comp ((Hom.α_hom X Y Z).whiskerLeft W)))
        ((Hom.α_hom (W.tensor X) Y Z).comp (Hom.α_hom W X (Y.tensor Z)))
  | triangle {X Y} :
      HomEquiv ((Hom.α_hom X unit Y).comp ((Hom.l_hom Y).whiskerLeft X))
        ((Hom.ρ_hom X).whiskerRight Y)
  -- START OF NAT'S STUFF
  | star {X Y} {f f' : X ⟶ᵐ Y} : HomEquiv f f' → HomEquiv f.star f'.star
  | starHom_id {X} : HomEquiv (Hom.id X).star (Hom.id X.star)
  | starHom_comp_starHom {X Y Z : F C} (f : X ⟶ᵐ Y) (g : Y ⟶ᵐ Z) :
    HomEquiv (f.comp g).star (f.star.comp g.star)
  | χ_hom_inv {X Y} : HomEquiv ((Hom.χ_hom X Y).comp (Hom.χ_inv X Y)) (Hom.id _)
  | χ_inv_hom {X Y} : HomEquiv ((Hom.χ_inv X Y).comp (Hom.χ_hom X Y)) (Hom.id _)
  | χ_naturality {X₁ X₂ Y₁ Y₂} (f : X₁ ⟶ᵐ Y₁) (g : X₂ ⟶ᵐ Y₂) :
    HomEquiv ((f.star.tensor g.star).comp (Hom.χ_hom Y₁ Y₂))
      ((Hom.χ_hom X₁ X₂).comp (g.tensor f).star)
  | ε_hom_inv {X} : HomEquiv ((Hom.ε_hom X).comp (Hom.ε_inv X)) (Hom.id _)
  | ε_inv_hom {X} : HomEquiv ((Hom.ε_inv X).comp (Hom.ε_hom X)) (Hom.id _)
  | ε_naturality {X Y : F C} (f : X ⟶ᵐ Y) :
    HomEquiv (f.star.star.comp (Hom.ε_hom Y)) ((Hom.ε_hom X).comp f)
  | f3 {P Q R : F C} : HomEquiv ((Hom.α_hom P.star Q.star R.star).comp <|
    ((Hom.χ_hom Q R).whiskerLeft P.star).comp <|
    (Hom.χ_hom P (R * Q)).comp (Hom.α_hom R Q P).star)
    (((Hom.χ_hom P Q).whiskerRight R.star).comp (Hom.χ_hom (Q * P) R))
  | n2 {P Q : F C} : HomEquiv ((Hom.χ_hom P.star Q.star).comp <|
    (Hom.χ_hom Q P).star.comp (Hom.ε_hom (P * Q)))
    ((Hom.ε_hom P).tensor (Hom.ε_hom Q))
  | a {R : F C} : HomEquiv (Hom.ε_hom R).star (Hom.ε_hom R.star)
  | twist_hom_inv {X} : HomEquiv ((Hom.twist_hom X).comp (Hom.twist_inv X)) (Hom.id _)
  | twist_inv_hom {X} : HomEquiv ((Hom.twist_inv X).comp (Hom.twist_hom X)) (Hom.id _)
  | twist_naturality {X Y : F C} (f : X ⟶ᵐ Y) :
    HomEquiv (f.star.comp (Hom.twist_hom Y)) ((Hom.twist_hom X).comp f)
  | tℓ {P Q R : F C} : HomEquiv
    (((Hom.χ_hom P.star Q.star).whiskerRight R.star.star).comp <|
      ((Hom.twist_hom (Q.star * P.star)).whiskerRight R.star.star).comp <|
      (Hom.α_hom Q.star P.star R.star.star).comp <|
      ((Hom.χ_hom P R.star).whiskerLeft Q.star).comp <|
      ((Hom.twist_hom (R.star * P)).whiskerLeft Q.star).comp <|
      (Hom.α_inv Q.star R.star P).comp <|
      ((Hom.χ_hom Q R).whiskerRight P).comp <|
      ((Hom.twist_hom (R * Q)).whiskerRight P).comp <|
      (Hom.α_hom R Q P))
    ((((Hom.twist_hom P.star).tensor (Hom.twist_hom Q.star)).tensor (Hom.twist_hom R.star)).comp <|
      ((Hom.χ_hom P Q).whiskerRight R.star).comp <|
      (Hom.χ_hom (Q * P) R).comp
      (Hom.twist_hom (R * (Q * P))))

def setoidHom (X Y : F C) : Setoid (X ⟶ᵐ Y) :=
  ⟨HomEquiv, ⟨HomEquiv.refl, HomEquiv.symm _ _, HomEquiv.trans⟩⟩

attribute [instance] setoidHom

/-
open CategoryTheory

instance (priority := low) prehom : CategoryStruct V where
  Hom := Hom
  id := Hom.id
  comp := Hom.comp

infixr:10 " ⟶ᵥ  " => prehom.Hom
notation "𝟙ᵥ" => prehom.id
infixr:80 " ≫ᵥ " => prehom.comp

-- synonym for Hom.Tensor that acts on the CategoryStruct notation
abbrev myTensor {W X Y Z : V} (f : W ⟶ᵥ Y) (g : X ⟶ᵥ Z) : (W * X) ⟶ᵥ  (Y * Z) := Hom.tensor f g
infixr:70 " ⊗ᵥ " => myTensor

abbrev myStar {X Y : V} (f : X ⟶ᵥ Y) : X⋆ ⟶ᵥ Y⋆ := Hom.star f
postfix:max "⋆ᵥ" => myStar

abbrev ς_hom (X : V) := Hom.twist_hom X
abbrev ς_inv (X : V) := Hom.twist_inv X

-- synonyms to make the monoidal category instance happy (IDK why Mathlib does it this way)
abbrev Hom.whiskerLeft (X : V) {Y₁ Y₂ : V} (f : Y₁ ⟶ᵥ Y₂) : (X * Y₁) ⟶ᵥ (X * Y₂) :=
  (𝟙ᵥ X) ⊗ᵥ f

abbrev Hom.whiskerRight {X₁ X₂ : V} (f : X₁ ⟶ᵥ X₂) (Y : V) : (X₁ * Y) ⟶ᵥ (X₂ * Y) :=
  f ⊗ᵥ (𝟙ᵥ Y)

infixr:81 " ◁ᵥ " => Hom.whiskerLeft
infixl:81 " ▷ᵥ " => Hom.whiskerRight

@[grind]
inductive HomEquiv : ∀ {A B : V}, (A ⟶ᵥ B) → (A ⟶ᵥ B) → Prop
  | refl (f : X ⟶ᵥ  Y) : HomEquiv f f
  | assoc {W X Y Z : V} (f : W ⟶ᵥ X) (g : X ⟶ᵥ Y) (h : Y ⟶ᵥ Z) :
      HomEquiv ((f ≫ᵥ g) ≫ᵥ h) (f ≫ᵥ (g ≫ᵥ h))
  | comp_id (f : X ⟶ᵥ Y) : HomEquiv (f ≫ᵥ (𝟙ᵥ _)) f
  | id_comp (f : X ⟶ᵥ Y) : HomEquiv ((𝟙ᵥ _) ≫ᵥ f) f
  -- congruence
  | comp {f f' : X ⟶ᵥ Y} {g g' : Y ⟶ᵥ Z} :
      HomEquiv f f' → HomEquiv g g' → HomEquiv (f ≫ᵥ g) (f' ≫ᵥ g')
  | tensor {f f' : W ⟶ᵥ X} {g g' : Y ⟶ᵥ Z} :
      HomEquiv f f' → HomEquiv g g' → HomEquiv (f ⊗ᵥ g) (f' ⊗ᵥ g')
  | star {f f' : X ⟶ᵥ Y} :
      HomEquiv f f' → HomEquiv f⋆ᵥ f'⋆ᵥ
  -- (bi)functoriality
  | id_tensor_id {X Y : V} : HomEquiv ((𝟙ᵥ X) ⊗ᵥ (𝟙ᵥ Y)) (𝟙ᵥ _)
  | tensor_comp_tensor (f₁ : X₁ ⟶ᵥ Y₁) (f₂ : X₂ ⟶ᵥ Y₂)
      (g₁ : Y₁ ⟶ᵥ Z₁) (g₂ : Y₂ ⟶ᵥ Z₂) :
      HomEquiv ((f₁ ⊗ᵥ f₂) ≫ᵥ (g₁ ⊗ᵥ g₂)) ((f₁ ≫ᵥ g₁) ⊗ᵥ (f₂ ≫ᵥ g₂))
  | star_id {X : V}: HomEquiv (𝟙ᵥ X)⋆ᵥ (𝟙ᵥ X⋆)
  | star_comp_star (f : X ⟶ᵥ Y) (g : Y ⟶ᵥ Z) :
      HomEquiv (f ≫ᵥ g)⋆ᵥ (f⋆ᵥ ≫ᵥ g⋆ᵥ)
  -- replacing the natural isomorphisms
  | tensor_assoc (f : P ⟶ᵥ Q) (g : W ⟶ᵥ X) (h : Y ⟶ᵥ Z) :
      HomEquiv (((f ⊗ᵥ g) ⊗ᵥ h) ≫ (eqToHom (mul_assoc Q X Z)))
        ((eqToHom (mul_assoc P W Y)) ≫ᵥ (f ⊗ᵥ(g ⊗ᵥ h)))
  | id_tensor (f : X ⟶ᵥ Y) :
      HomEquiv (((𝟙ᵥ 1) ⊗ᵥ f) ≫ᵥ (eqToHom (one_mul Y))) ((eqToHom (one_mul X)) ≫ f)
  | tensor_id (f : X ⟶ᵥ Y) :
      HomEquiv ((f ⊗ᵥ (𝟙ᵥ 1)) ≫ᵥ (eqToHom (mul_one Y))) ((eqToHom (mul_one X)) ≫ f)
  | star_skew (f : W ⟶ᵥ X) (g : Y ⟶ᵥ Z) :
      HomEquiv ((f⋆ᵥ ⊗ᵥ g⋆ᵥ) ≫ᵥ (eqToHom (StarMul.star_mul Z X).symm))
        ((eqToHom (StarMul.star_mul Y W).symm) ≫ (g ⊗ᵥ f)⋆ᵥ)
  | star_inv (f : X ⟶ᵥ Y) :
      HomEquiv (f⋆ᵥ⋆ᵥ ≫ (eqToHom (star_involutive Y))) ((eqToHom (star_involutive X)) ≫ᵥ f)
  -- special facts about the twist
  | twist_hom_inv :
      HomEquiv ((ς_hom X) ≫ᵥ (ς_inv X)) (𝟙ᵥ X)
  | twist_inv_hom :
      HomEquiv ((ς_inv X) ≫ᵥ (ς_hom X)) (𝟙 X⋆)
  | twist_naturality (f : X ⟶ᵥ Y) :
      HomEquiv (f⋆ᵥ ≫ᵥ (ς_inv Y)) ((ς_inv X) ≫ᵥ f)
  | tℓ (P Q R : V) : HomEquiv
      ((((eqToHom (StarMul.star_mul Q⋆ P⋆).symm) ≫ (ς_inv (Q⋆ * P⋆))) ⊗ᵥ (𝟙 R⋆⋆)) ≫
        (eqToHom (mul_assoc Q⋆ P⋆ R⋆⋆)) ≫ ((𝟙 Q⋆) ⊗ᵥ ((eqToHom (StarMul.star_mul R⋆ P).symm) ≫
        (ς_inv (R⋆ * P)))) ≫ (eqToHom (mul_assoc Q⋆ R⋆ P).symm) ≫
        (((eqToHom (StarMul.star_mul R Q).symm) ≫ (ς_inv (R * Q))) ⊗ᵥ (𝟙 P)) ≫
        (eqToHom (mul_assoc R Q P)))
      ((((ς_inv P⋆) ⊗ᵥ (ς_inv Q⋆)) ⊗ᵥ (ς_inv R⋆)) ≫
        ((eqToHom (StarMul.star_mul Q P).symm) ⊗ᵥ (𝟙 R⋆)) ≫
        (eqToHom (StarMul.star_mul R (Q * P)).symm) ≫ (ς_inv (R * (Q * P))))
  -- symm/trans last for constructor tactic
  | symm (f g : X ⟶ᵥ Y) : HomEquiv f g → HomEquiv g f
  | trans {f g h : X ⟶ᵥ Y} : HomEquiv f g → HomEquiv g h → HomEquiv f h

attribute [refl] HomEquiv.refl
attribute [symm] HomEquiv.symm

instance {A B : V} : HasEquiv (A ⟶ᵥ B) where
  Equiv := HomEquiv

-- helps grind slog through notation
@[grind =_]
lemma HomEquiv.equiv_def {X Y : V} {f g : X ⟶ᵥ Y} : HomEquiv f g ↔ f ≈ g := by
  constructor
  all_goals intros h
  all_goals exact h

lemma eqToHom_comp {X Y Z : V} {f : X ⟶ᵥ Y} {g : Y ⟶ᵥ Z} {p : X = Y} {q : Y = Z} :
    (f ≈ eqToHom p) → (g ≈ eqToHom q) → (f ≫ᵥ g) ≈ (eqToHom (p.trans q)) := by
  intros hf hg
  apply HomEquiv.trans
  · exact HomEquiv.comp hf hg
  · cases p
    cases q
    simp
    grind

lemma eqToHom_tensor {W X Y Z : V} {f : W ⟶ᵥ X} {g : Y ⟶ᵥ Z} {p : W = X} {q : Y = Z} :
    (f ≈ eqToHom p) → (g ≈ eqToHom q) → (f ⊗ᵥ g) ≈ (eqToHom (by simp [p, q])) := by
  intros hf hg
  apply HomEquiv.trans
  · exact HomEquiv.tensor hf hg
  · cases p
    cases q
    simp
    grind

lemma eqToHom_star {X Y : V} {f : X ⟶ᵥ Y} {p : X = Y} :
    (f ≈ eqToHom p) → f⋆ᵥ ≈ (eqToHom (by simp [p])) := by
  intros hf
  apply HomEquiv.trans
  · exact HomEquiv.star hf
  cases p
  simp
  grind

-- Attempts to take one step of simplifying a bunch of eqToHom/id to one eqToHom
macro "reduce_eqToHom_step" : tactic =>
  `(tactic|
    first
      | apply eqToHom_comp
      | apply eqToHom_tensor
      | apply eqToHom_star
      | rfl
  )

-- shows any combination of eqToHom/id is HomEquiv to a single eqToHom
macro "reduce_eqToHom" : tactic =>
  `(tactic|
    repeat' reduce_eqToHom_step
  )

-- shows any combinations of eqToHom/id HomEquiv to each other
macro "eqToHom_eq_eqToHom" : tactic =>
  `(tactic|
    apply HomEquiv.trans (by reduce_eqToHom) (by symm; reduce_eqToHom)
  )

lemma HomEquiv.whiskerLeft (X : V) {Y Z} {f f' : Y ⟶ Z} (h : f ≈ f') :
    (X ◁ᵥ f) ≈ (X ◁ᵥ f') := by grind

lemma HomEquiv.whiskerRight {X Y} {f f' : X ⟶ Y} (Z : V) (h : f ≈ f') :
    (f ▷ᵥ Z) ≈ (f' ▷ᵥ Z) := by grind

lemma HomEquiv.tensorHom_def {X₁ Y₁ X₂ Y₂ : V} (f : X₁ ⟶ᵥ Y₁) (g : X₂ ⟶ᵥ Y₂) :
    (f ⊗ᵥ g) ≈ (f ▷ᵥ X₂ ≫ᵥ Y₁ ◁ᵥ g) := by grind [tensor_comp_tensor]

lemma HomEquiv.whiskerLeft_id (X Y : V) : (X ◁ᵥ (𝟙 Y)) ≈ (𝟙 (X * Y)) := by
  grind

lemma HomEquiv.id_whiskerRight (X Y : V) : ((𝟙 X) ▷ᵥ Y) ≈ (𝟙 (X * Y)) := by
  grind

instance setoidHom (X Y : V) : Setoid (X ⟶ᵥ Y) :=
⟨HomEquiv, ⟨HomEquiv.refl, HomEquiv.symm _ _, HomEquiv.trans⟩⟩
-/

end FreeTwistedCategory
end CategoryTheory

