import Mathlib
import LeanCategory.FreeTwisted.Base
import LeanCategory.FreeTwisted.Instance

namespace CategoryTheory

variable (C : Type u)

open FreeTwistedCategory

/--
An object in Nat's definition of a free twisted category over
a quiver generated by a type `C`.
These have the same shape as the other objects; again we define
a new structure to avoid instance synthesis issues.
-/
structure NatDefinition where
  as : T C

namespace NatDefinition

variable {C : Type u}

@[inherit_doc NatDefinition]
scoped notation "N" => NatDefinition

abbrev of (c : C) : N C :=
  ⟨.of c⟩

abbrev unit : N C :=
  ⟨.unit⟩

abbrev tensor (X Y : N C) : N C :=
  ⟨X.as.tensor Y.as⟩

abbrev star (X : N C) : N C :=
  ⟨X.as.star⟩

open MonoidalCategory InvolutiveCategory

@[simp] lemma tensor_def {X Y : N C} : X.tensor Y = mk (X.as ⊗ Y.as) := rfl
@[simp] lemma star_def {X : N C} : X.star = mk (X.as⋆) := rfl
@[simp] lemma of_def (c : C) : of c = mk (.of c) := rfl
@[simp] lemma unit_def : @unit C = mk .unit := rfl

def map (f : C → D) (X : N C) : N D := ⟨X.as.map f⟩

@[simp] lemma map_as (f : C → D) (X : N C) : X.as.map f = (map f X).as := rfl

@[simp]
def sizeOf : N C → ℕ
  | ⟨X⟩ => X.sizeOf

variable [Quiver.{v} (T C)]

end CategoryTheory.NatDefinition

