import Mathlib
import LeanCategory.MonoidalWord

/-!
# Braid groupoid morphisms

This file defines the formal generators for morphisms in the braid groupoid.
-/

universe u

namespace BraidGroupoid

/-- Formal braids generated by crossings, associators, and unitors. -/
inductive Hom {α : Type u} : MonoidalWord α → MonoidalWord α → Type u
    | id (X : MonoidalWord α) : Hom X X
    | α_hom (X Y Z : MonoidalWord α) : Hom ((X.tensor Y).tensor Z) (X.tensor (Y.tensor Z))
    | α_inv (X Y Z : MonoidalWord α) : Hom (X.tensor (Y.tensor Z)) ((X.tensor Y).tensor Z)
    | l_hom (X) : Hom (MonoidalWord.unit.tensor X) X
    | l_inv (X) : Hom X (MonoidalWord.unit.tensor X)
    | ρ_hom (X) : Hom (X.tensor MonoidalWord.unit) X
    | ρ_inv (X) : Hom X (X.tensor MonoidalWord.unit)
    | σ (X Y : MonoidalWord α) : Hom (X.tensor Y) (Y.tensor X)
    | σ_inv (X Y : MonoidalWord α) : Hom (Y.tensor X) (X.tensor Y)
    | comp {X Y Z} (f : Hom X Y) (g : Hom Y Z) : Hom X Z
    | whiskerLeft (X : MonoidalWord α) {Y₁ Y₂} (f : Hom Y₁ Y₂) : Hom (X.tensor Y₁) (X.tensor Y₂)
    | whiskerRight {X₁ X₂} (f : Hom X₁ X₂) (Y : MonoidalWord α) :
        Hom (X₁.tensor Y) (X₂.tensor Y)
    | tensor {W X Y Z} (f : Hom W Y) (g : Hom X Z) : Hom (W.tensor X) (Y.tensor Z)

/-- Notation for braid morphisms. -/
scoped[ BraidGroupoid ] infixr:10 " ⟶ᵇ " => Hom

end BraidGroupoid
