import Mathlib
import LeanCategory.MonoidalWord

/-!
# Braid groupoid morphisms

This file defines the formal generators for morphisms in the braid groupoid.
-/

universe u

namespace BraidGroupoid

/-- Formal braids generated by crossings, associators, and unitors. -/
inductive Hom {α : Type u} : MonoidalWord α → MonoidalWord α → Type u
    | id (X : MonoidalWord α) : Hom X X
    | α_hom (X Y Z : MonoidalWord α) : Hom ((X.tensor Y).tensor Z) (X.tensor (Y.tensor Z))
    | α_inv (X Y Z : MonoidalWord α) : Hom (X.tensor (Y.tensor Z)) ((X.tensor Y).tensor Z)
    | l_hom (X) : Hom (MonoidalWord.unit.tensor X) X
    | l_inv (X) : Hom X (MonoidalWord.unit.tensor X)
    | ρ_hom (X) : Hom (X.tensor MonoidalWord.unit) X
    | ρ_inv (X) : Hom X (X.tensor MonoidalWord.unit)
    | σ (X Y : MonoidalWord α) : Hom (X.tensor Y) (Y.tensor X)
    | σ_inv (X Y : MonoidalWord α) : Hom (Y.tensor X) (X.tensor Y)
    | comp {X Y Z} (f : Hom X Y) (g : Hom Y Z) : Hom X Z
    -- | whiskerLeft (X : MonoidalWord α) {Y₁ Y₂} (f : Hom Y₁ Y₂) : Hom (X.tensor Y₁) (X.tensor Y₂)
    -- | whiskerRight {X₁ X₂} (f : Hom X₁ X₂) (Y : MonoidalWord α) :
        -- Hom (X₁.tensor Y) (X₂.tensor Y)
    | tensor {W X Y Z} (f : Hom W Y) (g : Hom X Z) : Hom (W.tensor X) (Y.tensor Z)

/-- Notation for braid morphisms. -/
scoped[ BraidGroupoid ] infixr:10 " ⟶ᵇ " => Hom

@[simp]
def Hom.whiskerLeft (X : MonoidalWord α) {Y₁ Y₂} (f : Y₁ ⟶ᵇ Y₂) : Hom (X.tensor Y₁) (X.tensor Y₂) :=
    Hom.tensor (Hom.id X) f

@[simp]
def Hom.whiskerRight {X₁ X₂} (f : X₁ ⟶ᵇ X₂) (Y : MonoidalWord α) : Hom (X₁.tensor Y) (X₂.tensor Y) :=
    Hom.tensor f (Hom.id Y)

open scoped BraidGroupoid

/-- Transport a shape assignment along a braid morphism. -/
-- TODO name is wrong (dang LLM)
@[simp]
def Hom.newMatch {α β : Type u} {X Y : MonoidalWord α} :
    (X ⟶ᵇ Y) → MonoidalWord.Match (α := α) β X → MonoidalWord.Match (α := α) β Y
    | Hom.id _, A => A
    | Hom.α_hom _ _ _, .tensor (.tensor A B) C => .tensor A (.tensor B C)
    | Hom.α_inv _ _ _, .tensor A (.tensor B C) => .tensor (.tensor A B) C
    | Hom.l_hom _, .tensor .unit A => A
    | Hom.l_inv _, A => .tensor .unit A
    | Hom.ρ_hom _, .tensor A .unit => A
    | Hom.ρ_inv _, A => .tensor A .unit
    | Hom.σ _ _, .tensor A B => .tensor B A
    | Hom.σ_inv _ _, .tensor B A => .tensor A B
    | Hom.comp f g, A => Hom.newMatch g (Hom.newMatch f A)
    -- | Hom.whiskerLeft _ f, .tensor A B => .tensor A (Hom.newMatch f B)
    -- | Hom.whiskerRight f _, .tensor A B => .tensor (Hom.newMatch f A) B
    | Hom.tensor f g, .tensor A B => .tensor (Hom.newMatch f A) (Hom.newMatch g B)

/-- The codomain word induced by `Hom.newMatch`. -/
def Hom.newCod {α β : Type u} {X Y : MonoidalWord α} :
    (X ⟶ᵇ Y) → MonoidalWord.Match (α := α) β X → MonoidalWord β
    | f, A => (Hom.newMatch f A).toMonoidalWord

/-- Enrich a braid morphism by replacing its labels with a chosen assignment. -/
def Hom.enrich {α β : Type u} {X Y : MonoidalWord α} :
    (f : X ⟶ᵇ Y) →
      (A : MonoidalWord.Match (α := α) β X) →
        (A.toMonoidalWord ⟶ᵇ f.newCod A)
    | Hom.id _, A => Hom.id (A.toMonoidalWord)
    | Hom.α_hom _ _ _, .tensor (.tensor A B) C =>
        Hom.α_hom A.toMonoidalWord B.toMonoidalWord C.toMonoidalWord
    | Hom.α_inv _ _ _, .tensor A (.tensor B C) =>
        Hom.α_inv A.toMonoidalWord B.toMonoidalWord C.toMonoidalWord
    | Hom.l_hom _, .tensor .unit A => Hom.l_hom A.toMonoidalWord
    | Hom.l_inv _, A => Hom.l_inv A.toMonoidalWord
    | Hom.ρ_hom _, .tensor A .unit => Hom.ρ_hom A.toMonoidalWord
    | Hom.ρ_inv _, A => Hom.ρ_inv A.toMonoidalWord
    | Hom.σ _ _, .tensor A B => Hom.σ A.toMonoidalWord B.toMonoidalWord
    | Hom.σ_inv _ _, .tensor B A => Hom.σ_inv A.toMonoidalWord B.toMonoidalWord
    | Hom.comp f g, A =>
        Hom.comp (Hom.enrich f A) (Hom.enrich g (Hom.newMatch f A))
    -- | Hom.whiskerLeft _ f, .tensor A B =>
    --     Hom.whiskerLeft A.toMonoidalWord (Hom.enrich f B)
    -- | Hom.whiskerRight f _, .tensor A B =>
    --     Hom.whiskerRight (Hom.enrich f A) B.toMonoidalWord
    | Hom.tensor f g, .tensor A B =>
        Hom.tensor (Hom.enrich f A) (Hom.enrich g B)

/-- Formal inverse on generators, reversing composition. -/
@[simp] -- TODO be cautious of this; IDK if it belongs
def Hom.inv {α : Type u} {X Y : MonoidalWord α} : Hom X Y → Hom Y X
    | Hom.id X => Hom.id X
    | Hom.α_hom X Y Z => Hom.α_inv X Y Z
    | Hom.α_inv X Y Z => Hom.α_hom X Y Z
    | Hom.l_hom X => Hom.l_inv X
    | Hom.l_inv X => Hom.l_hom X
    | Hom.ρ_hom X => Hom.ρ_inv X
    | Hom.ρ_inv X => Hom.ρ_hom X
    | Hom.σ X Y => Hom.σ_inv X Y
    | Hom.σ_inv X Y => Hom.σ X Y
    | Hom.comp f g => Hom.comp (Hom.inv g) (Hom.inv f)
    -- | Hom.whiskerLeft X f => Hom.whiskerLeft X (Hom.inv f)
    -- | Hom.whiskerRight f X => Hom.whiskerRight (Hom.inv f) X
    | Hom.tensor f g => Hom.tensor (Hom.inv f) (Hom.inv g)

end BraidGroupoid
